---
title: "Normal Probability Homework"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, error = TRUE)
```
<a href="../Downloads/Practice/Normal_Probability_Homework.qmd" download="../Downloads/Practice/Normal_Probability_Homework.qmd" type="text/markdown" download class="button-download">
    Download QMD
</a>

# The Normal Distribution

Recall that the normal distribution is a probability distribution defined by its center ($\mu$) and its spread ($\sigma$).  

[Insert examples of normal distributions with different means and standard deviations]

# Normal Probability Calculator

Use the calculator below to calculate the probabilities using the normal distribution.

```{r}

# Value
x <- 161

# Hypothesized Mean
mu <- 150.8

# Population Standard deviation
sigma <- 8.8

# Z-score:  number of standard deviations above the mean
z <- (x-mu) / sigma
z


# Probability of observing a z-score LESS THAN the one we observed (left tail)
pnorm(z)

# Probability of observing a z-score GREATER THAN the one we observed (Right Tail)
1-pnorm(z)


# For calculating the area between 2 numbers
A <- 61.5
B <- 68.5
pnorm(B, mu, sigma) - pnorm(A, mu, sigma)

# Find the X_bar associated with a spceific percentile
qnorm(.25, mu, sigma)

```



::: {.quiz}
What is the capital of France?

1. ( ) London
2. [ ] Berlin
3. [x] Paris
4. [ ] Madrid
:::
