---
title: "BYU-Idaho Math 221: Introduction to Statistics in R"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## A Customizable Textbook

This course is intended to familiarize students with foundational concepts and vocabulary in statistics and introduce basic data wrangling and visualization in R.

Those who diligently work through these materials will be well prepared for their next Statistics or Data Science course.

This book is designed to be a digital workbook.  You can download the Workbooks, Practice Problems and Application Activities which can be edited locally on your computer.  Completed workbooks and assignments will be submitted in Canvas as web-page reports.  


### Download Course Material

To download the folder containing all of the exercises, notes, R helps and Application Activities by following these steps:

  1. Create a class folder where you will save all your work throughout this semester.  This can be on your computer locally or in cloud-based storage such as One-Drive or iCloud.
  2. Click on the link below to download the `.zip` file containing all contents of the course website:
  
<a href="https://github.com/byuistats/Math221D_Course/archive/refs/heads/main.zip" class="button-download" download>
  Download Course Files
</a>

<a href="https://github.com/byuistats/Math221D_Course/raw/main/Student_Work.zip" class="button-download" download>
  Download Course Files
</a>

  2. Open the `.zip` file and the Folder called `Math221D_Course-main`
  3. Save the `Student_Work` folder to your class folder created in step 1.  This can typically be done by right clicking the folder then copying and pasting it into the new location. 

These files will be the basis of your coursework.  


### How to Use This Book

Each lesson will typically include:

  * Background readings (either from Stats Fundamentals or Workbooks)
  * Example code (mostly in Workbooks)
  * Opportunities to practice (Workbooks, Practice Problems and Application Activities)
  
Stats Fundamentals is a great reference for the core principles which are used throughout the course.  

Workbooks are more hands-on, interactive activities that reinforce and expand on the key topics from Stats Fundamentals.  

The Practice Problems tab provides opportunities to practice.  Sometimes these will be done in class with the assistance of teacher, TA, and friends.  Other times they will be completed on your own outside of class.  

Application Activities are designed to give you a more real-world experience dealing with data.  They are larger projects that may cover multiple lessons.

The section labeled "R Help" provides resources to help with R programming.


#### Suggested Sequence of Topics for Teaching

This book was specifically designed for the Math 221D section, Intro to Stats In R.

After introducing some foundational principles of Statistics, the recommended sequence:

1.  Course Introduction, including R installation
2.  Summarizing Data - Shape and Center
3.  Summarizing Data - Measures of Spread
4.  Probability
5.  Normal Distribution
6.  Distribution of Sample Means
7.  Probability Calculations for Means
8.  Introduction to Hypothesis Testing
9.  Introduction to Confidence Intervals
10. Inference for a Mean
11. Inference for Dependent Samples
12. Inference for Independent Samples
13. ANOVA
14. Regression
15. Distribution of $\hat{p}$
16. Inference for 1 Proportion
17. Inference for 2 Proportions
18. Chi Square Test for Independence


