---
title: 'Installing R'
output:
  html_document:
    theme: cerulean
    toc: true
    toc_float: false
format:
  html:
    self-contained: true
    code-fold: true
    page-layout: full
    title-block-banner: true
warning: false
---

# Installing R and RStudio

In this course, we will use R and RStudio to perform necessary calculations. This will allow us to focus on the statistical principles.

If you have not already installed R and RStudio on your computer, please follow these instructions to do so.

  1. Install R: Install the latest version of R [link](https://cran.r-project.org/)
  2. Install RStudio:	([Mac OS X](https://download1.rstudio.org/desktop/macos/RStudio-1.4.1106.dmg) | [PC](https://download1.rstudio.org/desktop/windows/RStudio-1.4.1106.exe))

If you are using a Chromebook or other “web browsing only” computer that will not allow you to install software, then set up an account at [RStudio Cloud](https://rstudio.cloud/) instead of installing R and RStudio as shown here.  Use your BYU-I

Just accept all of the default options when installing.

## Detailed Instructions

To install the statistical analysis program **RStudio** you will first need to install a piece of software called **R**. Funny name, right? (There was originally a software called “S” for statistics, and then “R” was invented later on. Part of the reason they used “R” was to claim that “R” was a “leap ahead” of “S.”)

Install the R Software by clicking:

  1. Mac OS X [M1-3 Chip](https://cran.r-project.org/bin/macosx/R-4.0.5.pkg) (Most Common)
  2. Mac OS X [Intel Chip](https://cran.r-project.org/bin/macosx/big-sur-x86_64/base/R-4.4.1-x86_64.pkg)
  3. [PC](https://cran.r-project.org/bin/windows/base/release.html)

Once that download finishes, open the resulting file.

Click “Continue” or “Okay” or “Accept” for all of the several various windows that will appear.

Now that R is properly installed on your computer, we need to install RStudio. RStudio is an app that runs R inside of it and provides you with many other tools that go way beyond what R can do. This is why R must be installed first, so that RStudio can use it. You will never need to open R yourself. Just use RStudio. But without R, RStudio won’t work properly.

Install the RStudio app by clicking here:	([Mac OS X](https://download1.rstudio.org/desktop/macos/RStudio-1.4.1106.dmg) | [Windows](https://download1.rstudio.org/electron/windows/RStudio-2024.04.2-764.exe)).



Once the RStudio installer downloads, open the resulting file.

Again, work through the installation process, agreeing with all the defaults and terms of conditions.

Once the installation finishes you can use your computer’s search bar to search for “RStudio” in your apps.

# Testing R-Studio

Throughout this course, you will download many files. The collection of files will be a valuable resource if you go on to use R in the future.

  1. Create a folder somewhere that is easy to find. Consider naming it "M221D" or another descriptive name
  2. Download the [TestingTesting.Rmd](https://github.com/byuistats/Math221D_Course/raw/main/01-Course_Intro/TestingTesting.qmd) file and save it into your folder. 
  3. Click the "Knit" or "Render" button at the top of the file that opens up

This should open up a browser window with some text and a chart. If it runs, you're technology is set up for success in this class. If not, ask Bracken or Brother Cannon for help.

# Troubleshooting 

## Mac Processing Chip

For Macs, Which version of R-Studio you download depends on which processing chip you have.  If you followed the instructions above and R-Studio opens but gives you a big error, you need to download the other version of R linked above.
