<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.543">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Math221 Notebook - Describing Quantitative Data (Spread)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Math221 Notebook</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-unit-1" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Unit 1</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-unit-1">    
        <li class="dropdown-header">Data Literacy</li>
        <li>
    <a class="dropdown-item" href="../1-Data_Literacy/1-Course_Introduction.html">
 <span class="dropdown-text">Course Introduction</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../1-Data_Literacy/2-Stat_Process.html">
 <span class="dropdown-text">The Statistical Process</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../1-Data_Literacy/3-Statistical_Process_Practice.html">
 <span class="dropdown-text">The Statistical Process-Practice</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../1-Data_Literacy/4-Installing_R.html">
 <span class="dropdown-text">Installing R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../1-Data_Literacy/5-Shape_and_Center.html">
 <span class="dropdown-text">Describing Quantitative Data (Shape &amp; Center)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../1-Data_Literacy/6-Spread.html">
 <span class="dropdown-text">Describing Quantitative Data (Spread)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../1-Data_Literacy/7-Introducing_R_Practice.html">
 <span class="dropdown-text">Introducing R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../1-Data_Literacy/8-Summarizing_Data_Multiple_Groups.html">
 <span class="dropdown-text">Summarizing Data Part 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../1-Data_Literacy/9-Summarizing_Data_Practice.html">
 <span class="dropdown-text">Summarizing Data Part 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../1-Data_Literacy/10-AA_Data_Summaries.html">
 <span class="dropdown-text">Summarizing Data AA</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-unit-2" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Unit 2</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-unit-2">    
        <li class="dropdown-header">Into the Tidyverse</li>
        <li>
    <a class="dropdown-item" href="../2-Tidy_Data/01-Wrangling_Basics.html">
 <span class="dropdown-text">Intro to Data Wrangling</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../2-Tidy_Data/02-Filter.html">
 <span class="dropdown-text">filter()</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../2-Tidy_Data/03-Select.html">
 <span class="dropdown-text">select()</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../2-Tidy_Data/05-Exploring_New_Data_with_Tidyverse.html">
 <span class="dropdown-text">Into The Tidyverse</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../2-Tidy_Data/06-GGPlot_Intro.html">
 <span class="dropdown-text">Introducing GGPlot!</span></a>
  </li>  
        <li class="dropdown-header">Bonus Material</li>
        <li>
    <a class="dropdown-item" href="../2-Tidy_Data/Bonus_More_Tidy_Practice.html">
 <span class="dropdown-text">Level up your Tidy-ness</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../2-Tidy_Data/Bonus_Mutate.html">
 <span class="dropdown-text">mutate()</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../2-Tidy_Data/Bonus_GroupBy_Summarise.html">
 <span class="dropdown-text">group_by() + summarise()</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-unit-3" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Unit 3</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-unit-3">    
        <li class="dropdown-header">Fundamentals of Statistics</li>
        <li>
    <a class="dropdown-item" href="../3-Stat_Fundamentals/01-Intro_to_Probability.html">
 <span class="dropdown-text">Intro to Probability</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../3-Stat_Fundamentals/02-The_Normal_Distribution_Textbook.html">
 <span class="dropdown-text">The Normal Distribution</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../3-Stat_Fundamentals/03-Normal_Distribution_Workbook.html">
 <span class="dropdown-text">The Normal Distribution</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../3-Stat_Fundamentals/04-Normal_Probability_Practice.html">
 <span class="dropdown-text">Normal Probability Homework</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../3-Stat_Fundamentals/05-The_Central_Limit_Theorem.html">
 <span class="dropdown-text">The Distribution of Sample Means</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../3-Stat_Fundamentals/06-Central_Limit_Theorem_Practice.html">
 <span class="dropdown-text">Central Limit Theorem</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../3-Stat_Fundamentals/07-Prob_Calculations_for_Means.html">
 <span class="dropdown-text">Calculating Probabilities involving the Sample Mean</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../3-Stat_Fundamentals/08-CLT_Normal_Prob_for_Means.html">
 <span class="dropdown-text">Normal Probability Calculations for Means</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../3-Stat_Fundamentals/09-Prob_Calculations_for_Means_Practice.html">
 <span class="dropdown-text">Calculating Probabilities with Means</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../3-Stat_Fundamentals/10-Assessing_Normality.html">
 <span class="dropdown-text">Assessing Normality</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-unit-4" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Unit 4</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-unit-4">    
        <li class="dropdown-header">Statistical Tests - Part 1</li>
        <li>
    <a class="dropdown-item" href="../4-Statistical_Tests_Part1/01-Inference_for_mean_sigma_unknown.html">
 <span class="dropdown-text">Inference for a Mean - Sigma Unknown</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../4-Statistical_Tests_Part1/02-AA_Hypothesis_Conf_Int.html">
 <span class="dropdown-text">Don’t Take it Personally</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../4-Statistical_Tests_Part1/03-Paired_ttest.html">
 <span class="dropdown-text">Paired T-test Class Notes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../4-Statistical_Tests_Part1/04-Paired_ttest_Practice.html">
 <span class="dropdown-text">Paired T-Test Practice</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../4-Statistical_Tests_Part1/05-Independent_2_sample_ttest.html">
 <span class="dropdown-text">Independent Two-sample T-test</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../4-Statistical_Tests_Part1/06-Independent_2_sample_ttest_practice.html">
 <span class="dropdown-text">2-Sample Independent T-Test Practice</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../4-Statistical_Tests_Part1/07-ANOVA_Intro.html">
 <span class="dropdown-text">Analysis of Variance (ANOVA)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../4-Statistical_Tests_Part1/08-ANOVA_Practice.html">
 <span class="dropdown-text">ANOVA Practice</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../4-Statistical_Tests_Part1/09-AA_Unit4_Review.html">
 <span class="dropdown-text">Comparing Means</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-unit-5" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Unit 5</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-unit-5">    
        <li class="dropdown-header">Statistical Tests - Part 2</li>
        <li>
    <a class="dropdown-item" href="../5-Statistical_Tests_Part2/01-Bivariate_Data_Intro.html">
 <span class="dropdown-text">Introducing the Bivariate Data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../5-Statistical_Tests_Part2/02-Linear_Regression_Intro.html">
 <span class="dropdown-text">Simple Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../5-Statistical_Tests_Part2/03-Regression_Practice.html">
 <span class="dropdown-text">Regression Practice</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../5-Statistical_Tests_Part2/Summarizing_Categorical_Data.html">
 <span class="dropdown-text">Summarizing Categorical Data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../5-Statistical_Tests_Part2/05-Distribution_of_Phat.html">
 <span class="dropdown-text">Sampling Distribution of P_hat</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../5-Statistical_Tests_Part2/06-Distribution_of_Phat_Practice.html">
 <span class="dropdown-text">Distribution of P-hat Practice</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../5-Statistical_Tests_Part2/07-One_Sample_Proportion_Ztest.html">
 <span class="dropdown-text">One-sample Proportion Tests</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../5-Statistical_Tests_Part2/08-One_Sample_Proportion_Practice.html">
 <span class="dropdown-text">One-sample Proportion Practice</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../5-Statistical_Tests_Part2/09-Two_Sample_Proportion_Ztest.html">
 <span class="dropdown-text">Two-sample Proportion Tests</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../5-Statistical_Tests_Part2/10-Two_Sample_Proportion_Practice.html">
 <span class="dropdown-text">2-Sample Proportion Practice</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../5-Statistical_Tests_Part2/11-Chi_Square_Intro.html">
 <span class="dropdown-text">Chi-square Test of Independence</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../5-Statistical_Tests_Part2/12-Chi_Square_Practice.html">
 <span class="dropdown-text">Chi-Square Practice</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../5-Statistical_Tests_Part2/13-AA_Who_Shot_First_Cat_Vars.html">
 <span class="dropdown-text">Who Shot First?</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-semester-project" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Semester Project</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-semester-project">    
        <li>
    <a class="dropdown-item" href="../6-Semester_Project/Semester_Project_Instructions.html">
 <span class="dropdown-text">Semester Project Instructions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../6-Semester_Project/Semester_Project_Template.html">
 <span class="dropdown-text">Semester Project</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../6-Semester_Project/Importing_Data.html">
 <span class="dropdown-text">Downloading Data</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-r-help" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">R Help</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-r-help">    
        <li>
    <a class="dropdown-item" href="https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf">
 <span class="dropdown-text">Tidyverse Cheat Sheet</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://r4ds.had.co.nz/transform.html">
 <span class="dropdown-text">R for Data Science</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../1-Data_Literacy/4-Installing_R.html">
 <span class="dropdown-text">Installing R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../2-Tidy_Data/06-GGPlot_Intro.html">
 <span class="dropdown-text">Introducing GGPlot!</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../2-Tidy_Data/01-Wrangling_Basics.html">
 <span class="dropdown-text">Intro to Data Wrangling</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../2-Tidy_Data/02-Filter.html">
 <span class="dropdown-text">filter()</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../2-Tidy_Data/03-Select.html">
 <span class="dropdown-text">select()</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../2-Tidy_Data/Bonus_Mutate.html">
 <span class="dropdown-text">mutate()</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../2-Tidy_Data/Bonus_GroupBy_Summarise.html">
 <span class="dropdown-text">group_by() + summarise()</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../6-Semester_Project/Importing_Data.html">
 <span class="dropdown-text">Downloading Data</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#lesson-outcomes" id="toc-lesson-outcomes" class="nav-link active" data-scroll-target="#lesson-outcomes">Lesson Outcomes</a></li>
  <li><a href="#spread-of-a-distribution" id="toc-spread-of-a-distribution" class="nav-link" data-scroll-target="#spread-of-a-distribution">Spread of a Distribution</a>
  <ul class="collapse">
  <li><a href="#standard-deviation-and-variance" id="toc-standard-deviation-and-variance" class="nav-link" data-scroll-target="#standard-deviation-and-variance">Standard Deviation and Variance</a></li>
  </ul></li>
  <li><a href="#additional-tools-to-describe-the-data" id="toc-additional-tools-to-describe-the-data" class="nav-link" data-scroll-target="#additional-tools-to-describe-the-data">Additional Tools to Describe the Data</a>
  <ul class="collapse">
  <li><a href="#percentiles-and-quartiles" id="toc-percentiles-and-quartiles" class="nav-link" data-scroll-target="#percentiles-and-quartiles">Percentiles and Quartiles</a></li>
  </ul></li>
  <li><a href="#summary-1" id="toc-summary-1" class="nav-link" data-scroll-target="#summary-1">Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Describing Quantitative Data (Spread)</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="lesson-outcomes" class="level2">
<h2 class="anchored" data-anchor-id="lesson-outcomes">Lesson Outcomes</h2>
<p>By the end of this lesson, you should be able to:</p>
<ol type="1">
<li>Calculate a percentile from data</li>
<li>Interpret a percentile</li>
<li>Calculate the standard deviation from data</li>
<li>Interpret the standard deviation</li>
<li>Calculate the five-number summary using software</li>
<li>Interpret the five-number summary</li>
<li>Create a box plot using software</li>
<li>Determine the five-number summary visually from a box plot</li>
</ol>
<p><br></p>
</section>
<section id="spread-of-a-distribution" class="level2">
<h2 class="anchored" data-anchor-id="spread-of-a-distribution">Spread of a Distribution</h2>
<p>In the previous lesson, we introduced two important characteristics of a distribution: the <strong>shape</strong> and the <strong>center</strong>. In this section, you will discover ways to summarize the <strong>spread</strong> of a distribution of data. The spread of a distribution of data describes how far the observations tend to be from each other. There are many ways to describe the spread of a distribution, but one of the most popular measurements of spread is called the “standard deviation.” <br></p>
<section id="standard-deviation-and-variance" class="level3">
<h3 class="anchored" data-anchor-id="standard-deviation-and-variance">Standard Deviation and Variance</h3>
<p>This activity introduces two measures of spread: the standard deviation and the variance.</p>
<p><img src="../Images/StepsAll.png"></p>
<p><strong>Bird Flu Fever </strong></p>
<p><img src="../Images/Peuquito.jpg"></p>
<p>Avian Influenza A H5N1, commonly called the bird flu, is a deadly illness that is currently only passed to humans from infected birds. This illness is particularly dangerous because at some point it is likely to mutate to allow human-to-human transmission. Health officials worldwide are preparing for the possibility of a bird flu pandemic.</p>
<p><img src="../Images/Step1.png"></p>
<p>Dr.&nbsp;K. Y. Yuen led a team of researchers who reported the body temperatures of people admitted to Chinese hospitals with confirmed cases of Avian Influenza. Their research team collected data on the body temperature at the time that people with the bird flu were admitted to the hospital. In the article, they reported on two groups of people, those with relatively uncomplicated cases of the bird flu and those with severe cases.</p>
<p><img src="../Images/Step2.png"></p>
<p>The table below presents the data representative of the body temperatures for the two groups of bird flu patients:</p>
<table class="table">
<thead>
<tr class="header">
<th>Body Temperature</th>
<th>Case Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>38.1</td>
<td>Simple</td>
</tr>
<tr class="even">
<td>38.3</td>
<td>Simple</td>
</tr>
<tr class="odd">
<td>38.4</td>
<td>Simple</td>
</tr>
<tr class="even">
<td>39.5</td>
<td>Simple</td>
</tr>
<tr class="odd">
<td>39.7</td>
<td>Simple</td>
</tr>
<tr class="even">
<td>39.1</td>
<td>Severe</td>
</tr>
<tr class="odd">
<td>39.5</td>
<td>Severe</td>
</tr>
<tr class="even">
<td>38.9</td>
<td>Severe</td>
</tr>
<tr class="odd">
<td>39.2</td>
<td>Severe</td>
</tr>
<tr class="even">
<td>39.9</td>
<td>Severe</td>
</tr>
<tr class="odd">
<td>39.7</td>
<td>Severe</td>
</tr>
<tr class="even">
<td>39.0</td>
<td>Severe</td>
</tr>
</tbody>
</table>
<p><img src="../Images/Step3.png"></p>
<p>Let us focus on the relatively uncomplicated cases. Creating a histogram of such a small dataset does not provide much benefit. With only a handful of values, there is not much shape to the distribution.</p>
<p>We can, however, use numerical summaries to give an indication of the center of the distribution.</p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="7" type="1">
<li>What is the median of the body temperatures for the simple cases? <!--Draw a vertical line on your number line to represent this point. --></li>
</ol>
<details>
<summary>
Solution
</summary>
<ul>
<li>The median body temperature for the simple cases is 38.4 degrees Centigrade.</li>
</ul>
</details>
<ol start="8" type="1">
<li>What is the mean of the body temperatures for the simple cases? <!--Draw a vertical line on your number line to represent this point. --></li>
</ol>
<details>
<summary>
Solution
</summary>
<ul>
<li>The mean body temperature for the simple cases is 38.8 degrees Centigrade.</li>
</ul>
</details>
</div>
<p><br></p>
<p>We will use these data to investigate some measures of the spread in a data set.</p>
<p>There is relatively little difference in the temperatures of the uncomplicated patients. The lowest is <span class="math inline">\(38.1 ^\circ \text{C}\)</span>, while the highest temperature is <span class="math inline">\(39.7 ^\circ \text{C}\)</span>.</p>
<p>The <strong>standard deviation</strong> is a measure of the <em>spread</em> in the distribution. If the data tend to be close together, then the standard deviation is relatively small. If the data tend to be more spread out, then the standard deviation is relatively large.</p>
<p>The standard deviation of the body temperatures is <span class="math inline">\(0.742 ^\circ \text{C}\)</span>. This number contains information from all the patients. If the patients’ temperatures had been more diverse, the standard deviation would be larger. If the patients’ temperatures were more uniform (i.e.&nbsp;closer together), then the standard deviation would have been smaller. If all the patients somehow had the same temperature, then the standard deviation would be zero.</p>
<p>We are working with a sample. To be explicit, we call <span class="math inline">\(0.742 ^\circ \text{C}\)</span> the <em>sample</em> standard deviation. The symbol for the sample standard deviation is <span class="math inline">\(s\)</span>. This is a statistic. The parameter representing the <em>population</em> standard deviation is <span class="math inline">\(\sigma\)</span> (pronounced /SIG-ma/). In practice, we rarely know the value of the population standard deviation, so we use the sample standard deviation <span class="math inline">\(s\)</span> as an approximation for the unknown population standard deviation <span class="math inline">\(\sigma\)</span>.</p>
<p>At this point, you probably do not have much intuition regarding the standard deviation. We will use this statistic frequently. By the end of the semester you can expect to become very comfortable with this idea. For now, all you need to know is that if two variables are measured on the same scale, the variable with values that are further apart will have the larger standard deviation.</p>
<div class="SoftwareHeading">
R Instructions
</div>
<div class="Software">
<p>&nbsp;&nbsp;<strong>To calculate the sample standard deviation in R, follow these steps:</strong> &nbsp;&nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">38.1</span>,<span class="fl">38.3</span>,<span class="fl">38.4</span>,<span class="fl">39.5</span>,<span class="fl">39.7</span>,<span class="fl">39.1</span>,<span class="fl">39.5</span>,<span class="fl">38.9</span>,<span class="fl">39.2</span>,<span class="fl">39.9</span>,<span class="fl">39.7</span>,<span class="fl">39.0</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5930788</code></pre>
</div>
</div>
<p><br></p>
</div>
<p><br></p>
<div class="message Tip">
<strong>Rounding:</strong> As a general rule, when reporting your answers in this class, round to three decimal places unless otherwise specified.
</div>
<p><br> <br></p>
<section id="calculating-the-standard-deviation-by-hand" class="level4">
<h4 class="anchored" data-anchor-id="calculating-the-standard-deviation-by-hand">Calculating the Standard Deviation by Hand</h4>
<p>How is the standard deviation computed? Where does this “magic” number come from? How does one number include the information about the spread of all the points?</p>
<p>It is a little tedious to compute the standard deviation by hand. You will usually compute standard deviation with a computer. However, the process is very instructive and will help you understand conceptually what the statistic represents. As you work through the following steps, please remember the goal is to find a measure of the spread in a data set. We want one number that describes how spread out the data are.</p>
<p>First, observe the number line below, where each x represents the temperature of a patient with a relatively uncomplicated case of bird flu. As mentioned earlier, there is not a huge spread in the temperatures.</p>
<p><img src="../Images/BirdFlu-DotPlotAnswer.png"></p>
<p>On your sketch of the number line, we draw a vertical line at 38.8 degrees, the sample mean. Now, draw horizontal lines from the mean to each of your <span class="math inline">\(\times\)</span>’s. These horizontal line segments represent the spread of the data about the mean. Your plot should look something like this:</p>
<p><img src="../Images/BirdFlu-DotPlotAnswer-Lines.png"></p>
<p>The length of each of the line segments represents how far each observation is from the mean. If the data are close together, these lines will be fairly short. If the distribution has a large spread, the line segments will be longer. The standard deviation is a measure of how long these lines are, as a whole.</p>
<p>The distance between the mean and an observation is referred to as a deviation. In other words, deviations are the lengths of the line segments drawn in the image above.</p>
<p><span class="math display">\[
\begin{array}{1cl}
\text{Deviation} &amp; = &amp; \text{Value} - \text{Mean} \\
\text{Deviation} &amp; = &amp; x - \bar x
\end{array}
\]</span></p>
<p>If the observed value is greater than the mean, the deviation is positive. If the value is less than the mean, the deviation is negative.</p>
<p>The standard deviation is a complicated sort of average of the deviations. Making a table like the one below will help you keep track of your calculations. Please participate fully in this exercise. Writing your answers at each step and developing a table as instructed will greatly enhance the learning experience. By following these steps, you will be able to compute the standard deviation by hand, and more importantly, understand what it is telling you.</p>
<p><strong>Step 01</strong>: The first step in computing the standard deviation by hand is to create a table, like the following. Enter the observed data in the first column.</p>
<center>
<table class="table">
<thead>
<tr class="header">
<th>
<p>
Observation (<span class="math inline">\(x\)</span>)
</p>

<p></p>
</th>
<th>
<p>
Deviation from the Mean (<span class="math inline">\(x-\bar x\)</span>)
</p>
</th>
</tr>
</thead>
<tbody>
<tr class="odd">
</tr>
<tr class="even">
<td>
<p>
<span class="math inline">\(38.1\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(38.1-38.8=-0.7\)</span>
</p>
</td>
</tr>
<tr class="odd">
<td>
<p>
<span class="math inline">\(38.3\)</span>
</p>
</td>
<td>
</td>
</tr>
<tr class="even">
<td>
<p>
<span class="math inline">\(38.4\)</span>
</p>
</td>
<td>
</td>
</tr>
<tr class="odd">
<td>
<p>
<span class="math inline">\(39.5\)</span>
</p>
</td>
<td>
</td>
</tr>
<tr class="even">
<td>
<p>
<span class="math inline">\(39.7\)</span>
</p>
</td>
<td>
</td>
</tr>
<tr class="odd">
<td>
<p>
<span class="math inline">\(\bar x = 38.8\)</span>
</p>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</center>
<p><strong>Step 02</strong>: The second column of the table contains the deviations from the mean. Complete column 2 of the table above.</p>
<a href="javascript:showhide('Step2')"><span style="font-size:8pt;">Check Results for Step 2</span></a>
<div id="Step2" style="display:none;">
<table>
<thead>
<tr class="header">
<th>
<p>
Observation (<span class="math inline">\(x\)</span>)
</p>
</th>
<th>
<p>
Deviation from the Mean (<span class="math inline">\(x-\bar x\)</span>)
</p>
</th>
</tr>
</thead>
<tbody>
<tr class="even">
<td>
<p>
<span class="math inline">\(38.1\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(38.1-38.8=-0.7\)</span>
</p>
</td>
</tr>
<tr class="odd">
<td>
<p>
<span class="math inline">\(38.3\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(38.3-38.8=-0.5\)</span>
</p>
</td>
</tr>
<tr class="even">
<td>
<p>
<span class="math inline">\(38.4\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(38.4-38.8=-0.4\)</span>
</p>
</td>
</tr>
<tr class="odd">
<td>
<p>
<span class="math inline">\(39.5\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(39.5-38.8=0.7\)</span>
</p>
</td>
</tr>
<tr class="even">
<td>
<p>
<span class="math inline">\(39.7\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(39.7-38.8=0.9\)</span>
</p>
</td>
</tr>
<tr class="odd">
<td>
<p>
<span class="math inline">\(\bar x = 38.8\)</span>
</p>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</div>
<p><br></p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="9" type="1">
<li>How could we use this table to find the “typical” distance from each point to the mean? Think carefully about this, and then write down your answer before continuing.</li>
</ol>
<details>
<summary>
Solution
</summary>
<ul>
<li>You may have suggested that we compute the mean of these values. This seems like a good idea. If we compute the mean, it will tell us the average deviation from the mean. <br></li>
</ul>
</details>
<p>9b. Compute the mean of Column 2. What do you get?</p>
<details>
<summary>
Solution
</summary>
<ul>
<li>You should have found that the mean of the deviations is zero. This is true for <em>every</em> data set. If you add up the deviations from the mean, the positive values will cancel with the negative values. The sum of the deviations from the mean will be zero, so the mean also must equal zero.</li>
<li>The good news is that you can use this fact to check if you are on the right track. If the deviations from the mean do not add up to zero, then you have made a mistake in the calculations. The bad news is that the deviations always add up to 0, making it look like the distance from the data to the mean is 0. Nonsense!</li>
<li>The mean of the deviations from the mean cannot be used to find a measure of the spread in a data set, but it does provide a guidepost that shows we are on the right track. We must find another way to estimate the spread of a data set.</li>
</ul>
</details>
<ol start="10" type="1">
<li>We need a way to work with the negative deviations from the mean, so they do not cancel with the positive ones. What could we do? (Choose one of the four options below.)</li>
</ol>
<details>
<summary>
Option 1: Take the absolute value of the deviations
</summary>
<ul>
<li><p>This is an excellent suggestion. This is probably one of the first things statisticians used to estimate the spread in the data.</p></li>
<li><p>If we take the absolute value of the deviations, then all the values are positive. By taking the mean of these numbers, we do get a measure of spread. This quantity is called the mean absolute deviation (MAD).</p></li>
<li><p>There is good news and bad news. The good news is, you discovered a way to estimate the spread in a data set. (In fact, the MAD is used as one estimate of the volatility of stocks.) The bad news is that the MAD does not have good theoretical properties. A proof of this claim requires calculus, and so will not be discussed here. For most applications, there is a better choice. Please select another option.</p></li>
</ul>
</details>
<details>
<summary>
Option 2: Square the deviations
</summary>
<ul>
<li>If we square the deviations from the mean, the values that were negative will become positive. This leads to an estimator of the spread that has excellent theoretical properties. This is the best of the four options. You will apply this idea in Step 03.</li>
</ul>
</details>
<details>
<summary>
Option 3: Delete the negative deviations
</summary>
<ul>
<li>Sorry, you can’t make your troubles go away by deleting things you don’t like. Please try again.</li>
</ul>
</details>
<details>
<summary>
Option 4: Do something entirely different
</summary>
<ul>
<li>You probably have an ingenious idea. Surprisingly enough, there <em>is</em> a right answer to the question. Please choose a different option.</li>
</ul>
</details>
<ul>
<li>Please do not go on to Step 03 until you have finished this exploration.</li>
</ul>
</div>
<p><br></p>
<center>
“Piled Higher and Deeper” by Jorge Cham <br> <img src="../Images/Phd062307s.png">
</center>
<p><strong>Step 03</strong>: Add a third column to your table. To get the values in this column, square the deviations from the mean that you found in Column 2.</p>
<table>
<thead>
<tr class="header">
<th>
<p>
Observation <span class="math inline">\(x\)</span>
</p>
</th>
<th>
<p>
Deviation<br> from the Mean<br> <span class="math inline">\(x-\bar x\)</span>
</p>
</th>
<th>
<p>
Squared Deviation<br> from the Mean<br> <span class="math inline">\(\left(x-\bar x\right)^2\)</span>
</p>
</th>
</tr>
</thead>
<tbody>
<tr class="even">
<td>
<p>
<span class="math inline">\(38.1\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(38.1-38.8=-0.7\)</span>
</p>
</td>
<td>
</td>
</tr>
<tr class="odd">
<td>
<p>
<span class="math inline">\(38.3\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(38.3-38.8=-0.5\)</span>
</p>
</td>
<td>
</td>
</tr>
<tr class="even">
<td>
<p>
<span class="math inline">\(38.4\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(38.4-38.8=-0.4\)</span>
</p>
</td>
<td>
</td>
</tr>
<tr class="odd">
<td>
<p>
<span class="math inline">\(39.5\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(39.5-38.8=0.7\)</span>
</p>
</td>
<td>
</td>
</tr>
<tr class="even">
<td>
<p>
<span class="math inline">\(39.7\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(39.7-38.8=0.9\)</span>
</p>
</td>
<td>
</td>
</tr>
<tr class="odd">
<td>
<p>
<span class="math inline">\(\bar x = 38.8\)</span>
</p>
</td>
<td>
<p>
Sum <span class="math inline">\(=0\)</span>
</p>
</td>
<td>
</td>
</tr>
</tbody>
</table>
<p><br></p>
<table>
<thead>
<tr class="header">
<th>
<p>
Observation <span class="math inline">\(x\)</span>
</p>
</th>
<th>
<p>
Deviation<br> from the Mean<br> <span class="math inline">\(x-\bar x\)</span>
</p>
</th>
<th>
<p>
Squared Deviation<br> from the Mean<br> <span class="math inline">\(\left(x-\bar x\right)^2\)</span>
</p>
</th>
</tr>
</thead>
<tbody>
<tr class="even">
<td>
<p>
<span class="math inline">\(38.1\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(38.1-38.8=-0.7\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\((-0.7)^2=0.49\)</span>
</p>
</td>
</tr>
<tr class="odd">
<td>
<p>
<span class="math inline">\(38.3\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(38.3-38.8=-0.5\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\((-0.5)^2=0.25\)</span>
</p>
</td>
</tr>
<tr class="even">
<td>
<p>
<span class="math inline">\(38.4\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(38.4-38.8=-0.4\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\((-0.4)^2=0.16\)</span>
</p>
</td>
</tr>
<tr class="odd">
<td>
<p>
<span class="math inline">\(9.5\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(39.5-38.8=0.7\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\((0.7)^2=0.49\)</span>
</p>
</td>
</tr>
<tr class="even">
<td>
<p>
<span class="math inline">\(39.7\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(39.7-38.8=0.9\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\((0.9)^2=0.81\)</span>
</p>
</td>
</tr>
<tr class="odd">
<td>
<p>
<span class="math inline">\(\bar x = 38.8\)</span>
</p>
</td>
<td>
<p>
Sum <span class="math inline">\(=0\)</span>
</p>
</td>
<td>
</td>
</tr>
</tbody>
</table>
<p><br></p>
<p><strong>Step 04</strong>: Now, add up the squared deviations from the mean.</p>
<table>
<thead>
<tr class="header">
<th>
<p>
Observation <span class="math inline">\(x\)</span>
</p>
</th>
<th>
<p>
Deviation<br> from the Mean<br> <span class="math inline">\(x-\bar x\)</span>
</p>
</th>
<th>
<p>
Squared Deviation<br> from the Mean<br> <span class="math inline">\(\left(x-\bar x\right)^2\)</span>
</p>
</th>
</tr>
</thead>
<tbody>
<tr class="even">
<td>
<p>
<span class="math inline">\(38.1\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(38.1-38.8=-0.7\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\((-0.7)^2=0.49\)</span>
</p>
</td>
</tr>
<tr class="odd">
<td>
<p>
<span class="math inline">\(38.3\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(38.3-38.8=-0.5\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\((-0.5)^2=0.25\)</span>
</p>
</td>
</tr>
<tr class="even">
<td>
<p>
<span class="math inline">\(38.4\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(38.4-38.8=-0.4\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\((-0.4)^2=0.16\)</span>
</p>
</td>
</tr>
<tr class="odd">
<td>
<p>
<span class="math inline">\(39.5\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(39.5-38.8=0.7\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\((0.7)^2=0.49\)</span>
</p>
</td>
</tr>
<tr class="even">
<td>
<p>
<span class="math inline">\(39.7\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(39.7-38.8=0.9\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\((0.9)^2=0.81\)</span>
</p>
</td>
</tr>
<tr class="odd">
<td>
<p>
<span class="math inline">\(\bar x = 38.8\)</span>
</p>
</td>
<td>
<p>
Sum <span class="math inline">\(=0\)</span>
</p>
</td>
<td>
<p>
Sum <span class="math inline">\(=2.20\)</span>
</p>
</td>
</tr>
</tbody>
</table>
<p>The sum of the squared deviations is 2.20. <br></p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="11" type="1">
<li>Suppose that the researchers had collected body temperature data on 500 bird flu patients instead of 5. What would happen to the sum of the squared deviations, if the distribution of the data is the same for the 500 patients as the 5 patients?</li>
</ol>
<details>
<summary>
Solution
</summary>
<ul>
<li>We would expect the sum of the squared deviations to be a lot larger than it is now. We would be adding squared deviations for 500 observations instead of 5. So, the sum of the squared deviations would be about 100 times larger.<br>
</li>
<li>Remember, we are trying to find a measure of the spread of a data set. Our final measure should not be dependent on the sample size. We need to do something else.</li>
</ul>
</details>
<ul>
<li>Please do not go on until you have finished this exercise.</li>
</ul>
</div>
<p><br></p>
<p><strong>Step 05</strong>: Recall that an average is adding a bunch of things up and dividing by the number of things. Consider taking the average of the squared deviations by adding them up and dividing by the number of deviations.</p>
<p>Unfortunately, this is what is technically known as a “biased” estimate. We don’t get into what that means in this class, but to correct for the bias, we divide by <span class="math inline">\(n-1\)</span> instead.</p>
<p>The number you computed in Step 05 is called the <span id="Sample Variance"><strong>sample variance</strong></span>. It is a measure of the spread in a data set. It has very nice theoretical properties. The variance plays an important role in Statistics. We denote the sample variance by the symbol <span class="math inline">\(s^2\)</span>.</p>
<p>It can be shown that the sample variance is an unbiased estimator of the true population variance (which is denoted <span class="math inline">\(\sigma^2\)</span>.) This means that the sample variance can be considered a reasonable estimator of the population variance. If the sample size is large, this estimator tends to be very good.</p>
<details>
<summary>
Results from Step 5
</summary>
<p>The sum of the squared deviations is the sum of the values in Column 3. This sum equals 2.20. We divide the sum of Column 3 (<span class="math inline">\(2.20\)</span>) by <span class="math inline">\(n-1=5-1=4\)</span> to get the sample variance, <span class="math inline">\(s^2\)</span>:</p>
<p><span class="math display">\[s^2=\frac{sum}{n-1}=\frac{2.20}{5-1}=0.55\]</span></p>
<p>This is the sample variance.</p>
<table>
<thead>
<tr class="header">
<th>
<p>
Observation <span class="math inline">\(x\)</span>
</p>
</th>
<th>
<p>
Deviation<br> from the Mean<br> <span class="math inline">\(x-\bar x\)</span>
</p>
</th>
<th>
<p>
Squared Deviation<br> from the Mean<br> <span class="math inline">\(\left(x-\bar x\right)^2\)</span>
</p>
</th>
</tr>
</thead>
<tbody>
<tr class="even">
<td>
<p>
<span class="math inline">\(38.1\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(38.1-38.8=-0.7\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\((-0.7)^2=0.49\)</span>
</p>
</td>
</tr>
<tr class="odd">
<td>
<p>
<span class="math inline">\(38.3\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(38.3-38.8=-0.5\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\((-0.5)^2=0.25\)</span>
</p>
</td>
</tr>
<tr class="even">
<td>
<p>
<span class="math inline">\(38.4\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(38.4-38.8=-0.4\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\((-0.4)^2=0.16\)</span>
</p>
</td>
</tr>
<tr class="odd">
<td>
<p>
<span class="math inline">\(39.5\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(39.5-38.8=0.7\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\((0.7)^2=0.49\)</span>
</p>
</td>
</tr>
<tr class="even">
<td>
<p>
<span class="math inline">\(39.7\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(39.7-38.8=0.9\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\((0.9)^2=0.81\)</span>
</p>
</td>
</tr>
<tr class="odd">
<td>
<p>
<span class="math inline">\(\bar x = 38.8\)</span>
</p>
</td>
<td>
<p>
Sum <span class="math inline">\(=0\)</span>
</p>
</td>
<td>
<p>
Sum <span class="math inline">\(=2.20\)</span>
</p>
</td>
</tr>
<tr class="even">
<td>
<p>
Variance:
</p>
</td>
<td>
<p>
<span class="math inline">\(\displaystyle{s^2=\frac{sum}{n-1}=\frac{2.20}{5-1}=0.55}\)</span>
</p>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<p><br></p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="13" type="1">
<li>The temperature data for the bird flu patients are in degrees Centigrade. What are the units of the variance?</li>
</ol>
<details>
<summary>
Solution
</summary>
<ul>
<li>The data in Column 1 of the table is in degrees Centigrade. The mean also is in degrees Centigrade.</li>
<li>To get the numbers in Column 2, we subtracted the mean from each of the values in Column 1.</li>
<li>We squared the values in Column 2 to get Column 3. The units for this column are degrees Centigrade squared.<br>
</li>
<li>The sum of the numbers in Column 3 will also be in units of degrees Centigrade squared.</li>
<li>When we divided that sum by <span class="math inline">\(n-1\)</span>, we obtained the sample variance. The sample variance has units of degrees Centigrade squared. This is not easily interpretable. It would be much easier to think about it if our measure of spread was in the same units as the data.</li>
</ul>
</details>
<ol start="14" type="1">
<li>What operation can we do to the variance to get a quantity with units degrees Centigrade?</li>
</ol>
<details>
<summary>
Solution
</summary>
<ul>
<li>If we take the square root of the variance, we get a quantity that has units of degrees Centigrade. This quantity is the standard deviation.</li>
</ul>
</details>
</div>
<p><br></p>
<p><strong>Step 06</strong>: Take the square root of the sample variance to get the sample standard deviation.</p>
<p>The sample standard deviation is defined as the square root of the sample variance.</p>
<p><span class="math display">\[\text{Sample Standard Deviation} = s = \sqrt{ s^2 } = \sqrt{\strut\text{Sample Variance}}\]</span></p>
<p>The standard deviation has the same units as the original observations. We use the standard deviation heavily in statistics.</p>
<p>The sample standard deviation (<span class="math inline">\(s\)</span>) is an estimate of the true population standard deviation (<span class="math inline">\(\sigma\)</span>).</p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="15" type="1">
<li>What is the sample standard deviation, <span class="math inline">\(s\)</span>, of the temperatures of the five patients with relatively uncomplicated cases of the bird flu?</li>
</ol>
<details>
<summary>
Solution
</summary>
<ul>
<li>The sum of the squared deviations is the sum of the values in Column 3. This sum equals 2.20. We divide the sum of Column 3 (<span class="math inline">\(2.20\)</span>) by <span class="math inline">\(n-1=5-1=4\)</span> to get the sample variance, <span class="math inline">\(s^2\)</span>:</li>
</ul>
<center>
<span class="math inline">\(s^2=\frac{sum}{n-1}=\frac{2.20}{5-1}=0.55\)</span>
</center>
<ul>
<li>This is the sample variance.</li>
</ul>
<table>
<thead>
<tr class="header">
<th>
<p>
Observation <span class="math inline">\(x\)</span>
</p>
</th>
<th>
<p>
Deviation<br> from the Mean<br> <span class="math inline">\(x-\bar x\)</span>
</p>
</th>
<th>
<p>
Squared Deviation<br> from the Mean<br> <span class="math inline">\(\left(x-\bar x\right)^2\)</span>
</p>
</th>
</tr>
</thead>
<tbody>
<tr class="even">
<td>
<p>
<span class="math inline">\(38.1\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(38.1-38.8=-0.7\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\((-0.7)^2=0.49\)</span>
</p>
</td>
</tr>
<tr class="odd">
<td>
<p>
<span class="math inline">\(38.3\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(38.3-38.8=-0.5\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\((-0.5)^2=0.25\)</span>
</p>
</td>
</tr>
<tr class="even">
<td>
<p>
<span class="math inline">\(38.4\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(38.4-38.8=-0.4\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\((-0.4)^2=0.16\)</span>
</p>
</td>
</tr>
<tr class="odd">
<td>
<p>
<span class="math inline">\(39.5\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(39.5-38.8=0.7\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\((0.7)^2=0.49\)</span>
</p>
</td>
</tr>
<tr class="even">
<td>
<p>
<span class="math inline">\(39.7\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(39.7-38.8=0.9\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\((0.9)^2=0.81\)</span>
</p>
</td>
</tr>
<tr class="odd">
<td>
<p>
<span class="math inline">\(\bar x = 38.8\)</span>
</p>
</td>
<td>
<p>
Sum <span class="math inline">\(=0\)</span>
</p>
</td>
<td>
<p>
Sum <span class="math inline">\(=2.20\)</span>
</p>
</td>
</tr>
<tr class="even">
<td>
<p>
Variance:
</p>
</td>
<td>
<p>
<span class="math inline">\(\displaystyle{s^2=\frac{sum}{n-1}=\frac{2.20}{5-1}=0.55}\)</span>
</p>
</td>
<td>
</td>
</tr>
<tr class="odd">
<td>
<p>
Standard Deviation:
</p>
</td>
<td>
<p>
<span class="math inline">\(\displaystyle{s = \sqrt{s^2}=\sqrt{0.55} \approx 0.742}\)</span>
</p>
</td>
<td>
</td>
</tr>
</tbody>
</table>
<ul>
<li><p>The sample standard deviation is <span class="math inline">\(s = 0.742\)</span> degrees Centigrade.</p></li>
<li><p>Take a few minutes to verify that you can recreate this table on your own.</p></li>
</ul>
</details>
</div>
<p><br></p>
</section>
<section id="summary" class="level4">
<h4 class="anchored" data-anchor-id="summary">Summary</h4>
<div class="Emphasis">
<p>&nbsp;&nbsp;<strong>Standard Deviation</strong></p>
<p>&nbsp;&nbsp;The <strong>standard deviation</strong> is one number that describes the spread in a set of data. If the data points are close together the standard deviation will be smaller than if they are spread out.</p>
<p>&nbsp;&nbsp;At this point, it may be difficult to understand the meaning and usefulness of the standard deviation. For now, it is enough for you to recognize the following points:</p>
<ul>
<li>The standard deviation is a measure of how spread out the data are.</li>
<li>If the standard deviation is large, then the data are very spread out.</li>
<li>If the standard deviation is zero, then all the values are the identical–there is no spread in the data.</li>
<li>The standard deviation cannot be negative. <br></li>
</ul>
</div>
<p><strong>Variance</strong></p>
<p>The variance is the square of the standard deviation. The sample variance is denoted by the symbol <span class="math inline">\(s^2\)</span>. You found the sample standard deviation for patient temperatures of uncomplicated cases of bird in the bird above is <span class="math inline">\(s = 0.74162\)</span>. So, the sample variance for this data set is <span class="math inline">\(s^2 = 0.74162^2 = 0.550\)</span>. Be aware, if you had squared the rounded value of <span class="math inline">\(s^2 = 0.742\)</span> in the calculation, you would have gotten an answer of 0.551 instead. This would be considered incorrect! <!-- [[NEED TO DISCUSS STATISTIC v. PARAMETER.]] --></p>
<div class="message Tip">
<strong>Rounding:</strong> Use <strong>un</strong>rounded values in interim calculations. Rounding too early in the process can lead to wrong answers.
</div>
<p><br> <br></p>
<div class="SoftwareHeading">
R Instructions
</div>
<div class="Software">
<p>&nbsp;&nbsp;<strong>To calculate the sample variance in R:</strong> &nbsp;&nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">38.1</span>,<span class="fl">38.3</span>,<span class="fl">38.4</span>,<span class="fl">39.5</span>,<span class="fl">39.7</span>,<span class="fl">39.1</span>,<span class="fl">39.5</span>,<span class="fl">38.9</span>,<span class="fl">39.2</span>,<span class="fl">39.9</span>,<span class="fl">39.7</span>,<span class="fl">39.0</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3517424</code></pre>
</div>
</div>
<p><br></p>
</div>
<p><br></p>
<p>The standard deviation and variance are two commonly used measures of the spread in a data set. Why is there more than one measure of the spread? The standard deviation and the variance each have their own pros and cons.</p>
<p>The variance has excellent theoretical properties. It is an unbiased estimator of the true population variance. That means that if many, many samples of <span class="math inline">\(n\)</span> observations were drawn, the variances computed for all the samples would be centered nicely around the true population variance, <span class="math inline">\(\sigma^2\)</span>. Because of these benefits, the variance is regularly used in higher-level statistics applications. One drawback of the variance is that the units for the variance are the square of the units for the original data. In the bird flu example, the body temperatures were measured in degrees Centigrade. So, the variance will have units of degrees Centigrade squared <span class="math inline">\((^\circ \text{C})^2\)</span>. What does degrees Centigrade squared mean? How do you interpret this? It doesn’t make any sense. This is one of the major drawbacks of the sample variance.</p>
<p>Because we take the square root of the variance to get the standard deviation, the standard deviation is in the same units as the original data. This is a great advantage, and is one of the reasons that the standard deviation is commonly used to describe the spread of data.</p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<p>Enter the patient temperature data for the severe cases of bird flu into R Then use R to calculate the numerical summaries you have learned so far. As a reminder, the temperatures of patients with a severe case of bird flu are:</p>
<center>
39.1, 39.5, 38.9, 39.2, 39.9, 39.7, 39
</center>
<ol start="16" type="1">
<li>What is the mean, median, standard deviation and variance of the sample?</li>
</ol>
<details>
<summary>
Solution
</summary>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>bird_flu <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">39.1</span>, <span class="fl">39.5</span>, <span class="fl">38.9</span>, <span class="fl">39.2</span>, <span class="fl">39.9</span>, <span class="fl">39.7</span>, <span class="dv">39</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(bird_flu)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 39.32857</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(bird_flu)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 39.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(bird_flu)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.377334</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(bird_flu)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.142381</code></pre>
</div>
</div>
</details>
<p><br></p>
<p>For the next two questions, consider the histograms below comparing weight (in kilograms) of men (top histogram) to elephant seals (bottom histogram).</p>
<p><br></p>
<div style="padding-left:35px;">
<p>Weight of Men Compared to Weight of Seals<br> <img src="../Images/DiveSealsVsMenWeights-Hist.png" width="80%"></p>
</div>
<ol start="17" type="1">
<li>Based on the histograms, who has a greater sample mean weight, men or elephant seals?</li>
</ol>
<details>
<summary>
Solution
</summary>
<ul>
<li>The mean is a measure of the center of a distribution. The mean weight of the men is less than the mean weight of the seals. We can see this because the bulk of the data in the histogram for the men’s weight is to the left of the seals’. The center of the distribution of elephant seals is about 195 kg. The center of the distribution of men’s weight is located below 100 kg on the number line.</li>
</ul>
</details>
<p><br></p>
<ol start="18" type="1">
<li>Based on the histograms, do the weights of men or elephant seals have a larger sample standard deviation?</li>
</ol>
<details>
<summary>
Solution
</summary>
<ul>
<li>Standard deviation is a measure of spread. You will note that the weights of the seals are more spread out than the weights of the men. Therefore, we conclude that the sample standard deviation of elephant seal weights is larger than the sample standard deviation of men’s weights.</li>
</ul>
</details>
<p>&nbsp;</p>
</div>
<p><br></p>
<p><strong>Review of Parameters and Statistics</strong></p>
<p>We have now learned some statistics that can be used to estimate population parameters. For example, we use <span class="math inline">\(\bar x\)</span> to estimate the population mean <span class="math inline">\(\mu\)</span>. The sample statistics <span class="math inline">\(s\)</span> estimates the true population standard deviation <span class="math inline">\(\sigma\)</span>. The following table summarizes what we have done so far:</p>
<center>
<table class="table">
<thead>
<tr class="header">
<th>
</th>
<th>
<p>
Sample Statistic
</p>
</th>
<th>
<p>
Population Parameter
</p>
</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>
<p>
Mean
</p>
</td>
<td>
<p>
<span class="math inline">\(\bar x\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(\mu\)</span>
</p>
</td>
</tr>
<tr class="even">
<td>
<p>
Standard Deviation
</p>
</td>
<td>
<p>
<span class="math inline">\(s\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(\sigma\)</span>
</p>
</td>
</tr>
<tr class="odd">
<td>
<p>
Variance
</p>
</td>
<td>
<p>
<span class="math inline">\(s^2\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(\sigma^2\)</span>
</p>
</td>
</tr>
<tr class="even">
<td>
<p>
<span class="math inline">\(\vdots\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(\vdots\)</span>
</p>
</td>
<td>
<p>
<span class="math inline">\(\vdots\)</span>
</p>
</td>
</tr>
</tbody>
</table>
</center>
<p>Unless otherwise specified, we will always use Rto find the sample variance and sample mean. In each case, the sample statistic estimates the population parameter. The ellipses <span class="math inline">\(\vdots\)</span> in this table hint that we will add rows in the future.</p>
<p><br></p>
<p><strong>Optional Reading: Formulas for <span class="math inline">\(s\)</span> and <span class="math inline">\(s^2\)</span> (Hidden)</strong></p>
<details>
<summary>
Click here if you love math
</summary>
<p><strong>Formulas</strong></p>
<p>For those who like formulas, the equation for the sample variance and sample standard deviation are given here.</p>
<p><strong>Sample variance</strong>:</p>
<p><span class="math display">\[\displaystyle{ s^2=\frac{\sum\limits_{i=1}^n (x_i-\bar x)^2}{n-1} }\]</span></p>
<p><strong>Sample standard deviation</strong>:</p>
<p><span class="math display">\[\displaystyle{ s=\sqrt{s^2}=\sqrt{\frac{\sum\limits_{i=1}^n (x_i-\bar x)^2}{n-1}} }\]</span></p>
<p>where <span class="math inline">\(x_i\)</span> is the <span class="math inline">\(i^{th}\)</span> observed data value, and <span class="math inline">\(i=1, 2, \ldots, n\)</span>.</p>
<p>Unless otherwise specified, we will always use Excel<!--{{Course_Filter|course=B C|content=SPSS}}--> to find the sample variance and sample mean.</p>
<p><strong>Why do we divide by <span class="math inline">\(n-1\)</span>?</strong></p>
When computing the standard deviation or the variance, we are finding a value that describes the spread of data values. It is a measure of how far the data are from the mean. Since we do not know the true mean (<span class="math inline">\(\mu\)</span>,) we use the sample mean (<span class="math inline">\(\bar x\)</span>,) to estimate it. Typically, the data will be closer to <span class="math inline">\(\bar x\)</span> than to <span class="math inline">\(\mu\)</span>, since <span class="math inline">\(\bar x\)</span> was computed using the data. To compensate for this, we divide by <span class="math inline">\(n-1\)</span> rather than <span class="math inline">\(n\)</span> when we find the “average” of the squared deviations from the mean. It turns out, that subtracting 1 from <span class="math inline">\(n\)</span> inflates this average by the precise amount needed to compensate for the use of <span class="math inline">\(\bar x\)</span> as an estimate for <span class="math inline">\(\mu\)</span>. As a result, the sample variance (<span class="math inline">\(s^2\)</span>) is a good estimator of the population variance (<span class="math inline">\(\sigma^2\)</span>.)
</details>
<p><br></p>
<p>Neither the standard deviation nor the variance is <strong>resistant</strong> to outliers. This means that when there are outliers in the data set, the standard deviation and the variance become artificially large. It is worth noting that the mean is also not resistant. When there are outliers, the mean will be “pulled” in the direction of the outliers.</p>
<p>The mean and standard deviation are used to describe the center and spread when the distribution of the data is symmetric and bell-shaped. If data are not symmetric and bell-shaped, we typically use the five-number summary (discussed below) to describe the spread, because this summary is resistant.</p>
</section>
</section>
</section>
<section id="additional-tools-to-describe-the-data" class="level2">
<h2 class="anchored" data-anchor-id="additional-tools-to-describe-the-data">Additional Tools to Describe the Data</h2>
<p>Recall the five steps of the Statistical Process (and the mnemonic “Daniel Can Discern More Truth).</p>
<center>
<table class="table">
<tbody>
<tr class="odd">
<td>
<p>
Step 1:
</p>
</td>
<td>
<p>
<strong>D</strong>aniel
</p>
</td>
<td>
<p>
<strong>D</strong>esign the study
</p>
</td>
</tr>
<tr class="even">
<td>
<p>
Step 2:
</p>
</td>
<td>
<p>
<strong>C</strong>an
</p>
</td>
<td>
<p>
<strong>C</strong>ollect data
</p>
</td>
</tr>
<tr class="odd">
<td>
<p>
Step 3:
</p>
</td>
<td>
<p>
<strong>D</strong>iscern
</p>
</td>
<td>
<p>
<strong>D</strong>escribe the data
</p>
</td>
</tr>
<tr class="even">
<td>
<p>
Step 4:
</p>
</td>
<td>
<p>
<strong>M</strong>ore
</p>
</td>
<td>
<p>
<strong>M</strong>ake inferences
</p>
</td>
</tr>
<tr class="odd">
<td>
<p>
Step 5:
</p>
</td>
<td>
<p>
<strong>T</strong>ruth
</p>
</td>
<td>
<p>
<strong>T</strong>ake action
</p>
</td>
</tr>
</tbody>
</table>
<img src="../Images/StepsAll.png">
</center>
<p><strong>Step 3</strong> of this process is “<strong>Describe the data</strong>.” You have already learned about the mean, median, mode, standard deviation, variance and histograms. These can be good ways to describe the data. The following information on percentiles, quartiles, 5-number summaries, and boxplots will help you learn other common ways to describe data, especially if the data are skewed or contain outliers.</p>
<p><img src="../Images/Step3.png"></p>
<p>For symmetric, bell-shaped data, the mean and standard deviation provide a good description of the center and shape of the distribution. The mean and standard deviation are not sufficient to describe a distribution that is skewed or has outliers. An <strong>outlier</strong> is any observation that is very far from the others. The mean is pulled in the direction of the outlier. Also, the standard deviation is inflated by points that are very far from the mean.</p>
<p>Now, you have probably had some experience with percentiles in the past especially when you received a score on a standardized test such as the ACT. Even though percentiles are commonly used, they are generally misunderstood. Before examining the wrong site/wrong patient data, let’s review percentiles. Even if you think you understand percentiles, please study this section carefully.</p>
<p><br></p>
<section id="percentiles-and-quartiles" class="level3">
<h3 class="anchored" data-anchor-id="percentiles-and-quartiles">Percentiles and Quartiles</h3>
<p>Imagine a very long street with houses on one side. The houses increase in value from left to right. At the left end of the street is a small cardboard box with a leaky roof. Next door is a slightly larger cardboard box that does not leak. The houses eventually get larger and more valuable. The rightmost house on the street is a huge mansion.</p>
<div class="QuestionsHeading">
Answer the following question:
</div>
<div class="Questions">
<ol start="19" type="1">
<li>There are 100 homes with increasing property values. How many fences are needed to separate the 100 properties?</li>
</ol>
<details>
<summary>
Solution
</summary>
<ul>
<li>In order to separate the 100 homes, 99 fences are required.</li>
</ul>
</details>
</div>
<p><br></p>
<p>The home values are representative of data. If we have a list of data, sorted in increasing order, and we want to divide it into 100 equal groups, we only need 99 dividers (like fences) to divide up the data. The first divider is as large or larger than 1% of the data. The second divider is as large or larger than 2% of the data, and so on. The last divider, the 99<sup>th</sup>, is the value that is as large or larger than 99% of the data. These dividers are called percentiles. A <strong>percentile</strong> is a number such that a specified percentage of the data are at or below this number. For example, the 99<sup>th</sup> percentile is a number such that 99% of the data are at or below this value. As another example, half (50%) of the data lie at or below the 50<sup>th</sup> percentile. The word percent means <span class="math inline">\(\div 100\)</span>. This can help you remember that the percentiles divide the data into 100 equal groups.</p>
<p><strong>Quartiles</strong> are special percentiles. The word quartile is from the Latin <em>quartus</em>, which means “fourth.” The quartiles divide the data into four equal groups. The quartiles correspond to specific percentiles. The first quartile, Q<sub>1</sub>, is the 25<sup>th</sup> percentile. The second quartile, Q<sub>2</sub>, is the same as the 50<sup>th</sup> percentile or the median. The third quartile, Q<sub>3</sub>, is equivalent to the 75<sup>th</sup> percentile.</p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="20" type="1">
<li>How many quartiles are there?</li>
</ol>
<details>
<summary>
Solution
</summary>
<ul>
<li>There are 3 quartiles! To divide the data into 100 equal groups, we needed 99 percentiles. To divide the data into 4 equal groups, we need 3 quartiles.
</li></ul></details></div>
&nbsp;


<p><br></p>
<p><strong>Wrong Site/Wrong Patient Lawsuits</strong></p>
<p>Percentiles can be used to describe the center and spread of any distribution and are particularly useful when the distribution is skewed or has outliers. To explore this issue, you will use software to calculate percentiles of data on costs incurred by hospitals due to certain lawsuits. The lawsuits in question were about surgeries performed on the wrong patient, or on the right patient but the wrong part of the patient’s body (the wrong site).</p>
<p>But first, we need to learn how to load data into R.</p>
<p>R has many built-in toolboxes. R also has a vast array of toolboxes beyond the built-in ones that we must first install. This is like going to the Home Depot to buy a specialized toolbox and then storing it in your garage. We only have to “buy” it once.</p>
<p>To install a library, we use the <code>install.packages("")</code> command, where we specify the library we want in the quotes inside the parentheses.</p>
<p><code>rio</code> is a toolbox that is very useful for loading data into R. If you haven’t already done so, install the <code>rio</code> library.</p>
<pre><code>install.packages('rio')</code></pre>
<p>While you only have to install libraries once, you have to load them every time you want to use one. It’s like going to the garage to get the toolbox you need for the job.</p>
<p>Now let’s load the data and calculate some percentiles!</p>
<div class="SoftwareHeading">
R Instructions
</div>
<div class="Software">
<ul>
<li>Open R and load the <code>rio</code> library:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Use the <code>import()</code> function to load the dataset:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>wrong_site <span class="ot">&lt;-</span> <span class="fu">import</span>(<span class="st">"https://github.com/byuistats/Math221D_Course/raw/main/Data/WrongSiteWrongPatient.xlsx"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>&nbsp;&nbsp;<strong>To calculate percentiles and quartiles in R, do the following</strong></p>
<ul>
<li>Datasets loaded into R may have many columns of information. To specify which column in the dataset should be used for analysis we use the <code>$</code>. For example, if we wanted only to look at the Wrong_Patient clumn in the wrong_site dataset:</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  [1]  250000  106900   62307  192800   20769    2680    4300   30819   23214
 [10]   26099       0   50000   66600  175000   10384   42900   52928       0
 [19]    8200    2500    6900  126300     900    7700  140000   76000   50000
 [28]  354530    5359    4300   12000   16749   35600    9045   21900    2010
 [37]   22444   50000   85000   40370   39863       0   36100   49000   48908
 [46]   19800   32200    3400       0   75000   21774    2600   30000    7300
 [55]  176940   55000    9500   55272    4690   75000   34168   83700    1005
 [64]   17419   34800   14739       0       0    1000     325   41538  108200
 [73]   63224   15000       0    3900   65657   50000  109205    3900   10000
 [82]    9900   87096   12090       0    1000       0   74701    3900   18000
 [91]       0   33499    1250       0   29813   11724  141363    3685   35508
[100]    2500   12060    5695   50582   82071   55400       0  104400     500
[109]       0   25000   10000   85000   25000       0   24100    3900 1250000
[118]   15074     550    7195  101800   11600    1000    4020   19764   25794
[127]     900   10000   35200   94100       0   16909  128400   60967   50000
[136]   50000   84751   46800  130308   43800   49242   22800   15500   11054
[145]     400   10000  104790   13064    6400  100000   17084   16300   11000
[154]   12500       0    1200       0  200000    3900    3015  172200   25000
[163]   27468  250000   21104   12500   30000   59000   46227     500  131000
[172]    2345    6000       0     670    9714      NA      NA      NA      NA
[181]      NA      NA      NA      NA      NA      NA      NA      NA      NA
[190]      NA      NA      NA      NA      NA      NA      NA      NA      NA
[199]      NA      NA      NA      NA      NA      NA      NA      NA      NA
[208]      NA      NA      NA      NA      NA      NA      NA      NA      NA
[217]      NA      NA      NA      NA      NA      NA      NA      NA      NA
[226]      NA      NA      NA      NA      NA      NA      NA      NA      NA
[235]      NA      NA      NA      NA      NA      NA      NA      NA      NA
[244]      NA      NA      NA      NA      NA      NA      NA      NA      NA
[253]      NA      NA      NA      NA      NA      NA      NA      NA      NA
[262]      NA      NA      NA      NA      NA      NA      NA      NA      NA
[271]      NA      NA      NA      NA      NA      NA      NA      NA      NA
[280]      NA      NA      NA      NA      NA      NA      NA      NA      NA
[289]      NA      NA      NA      NA      NA      NA      NA      NA      NA
[298]      NA      NA      NA      NA      NA      NA      NA      NA      NA
[307]      NA      NA      NA      NA      NA      NA      NA      NA      NA
[316]      NA      NA      NA      NA      NA      NA      NA      NA      NA
[325]      NA      NA      NA      NA      NA      NA      NA      NA      NA
[334]      NA      NA      NA      NA      NA      NA      NA      NA      NA
[343]      NA      NA      NA      NA      NA      NA      NA      NA      NA
[352]      NA      NA      NA      NA      NA      NA      NA      NA      NA
[361]      NA      NA      NA      NA      NA      NA      NA      NA      NA
[370]      NA      NA      NA      NA      NA      NA      NA      NA      NA
[379]      NA      NA      NA      NA      NA      NA      NA      NA      NA
[388]      NA      NA      NA      NA      NA      NA      NA      NA      NA
[397]      NA      NA      NA      NA      NA      NA      NA      NA      NA
[406]      NA      NA      NA      NA      NA      NA</code></pre>
</div>
</div>
<ul>
<li><p>Use R’s <code>quantile()</code> function. This functions requires two inputs separated by a comma: the data and the desired percentile input as a decimal.</p></li>
<li><p>To calculate the 25th percentile for the costs of surgery done on the Wrong Site:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(wrong_site<span class="sc">$</span>Wrong_Site, .<span class="dv">25</span>, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  25% 
29496 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Note: the na.rm=TRUE removes the missing values from the dataset</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
</div>
<p><br></p>
<p>The first quartile (<span class="math inline">\(Q_1\)</span>) or 25<sup>th</sup> percentile (calculated in R) of the wrong-site data is: $29,496. (This result is illustrated in the figure below.) This means that 25 percent of the time hospitals lost a wrong-site lawsuit, they had to pay $29,496 or less. The 25<sup>th</sup> percentile can be written symbolically as: P<sub>25</sub> = $29,496. Other percentiles can be written the same way. The 99<sup>th</sup> percentile can be written as P<sub>99</sub>.</p>
<center>
<strong>Percentiles (Calculated in Excel)</strong>
</center>
<table class="table">
<thead>
<tr class="header">
<th>&nbsp;</th>
<th>&nbsp;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1st percentile</td>
<td>0</td>
</tr>
<tr class="even">
<td>2nd percentile</td>
<td>0</td>
</tr>
<tr class="odd">
<td>3rd percentile</td>
<td>0</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>24th percentile</td>
<td>28633.4</td>
</tr>
<tr class="even">
<td>25th percentile</td>
<td>29496</td>
</tr>
<tr class="odd">
<td>26th percentile</td>
<td>31067</td>
</tr>
</tbody>
</table>
<p><br></p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="21" type="1">
<li>What is the 13<sup>th</sup> percentile of the wrong site data?</li>
</ol>
<details>
<summary>
Solution
</summary>
<ul>
<li>$6343.40</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(wrong_site<span class="sc">$</span>Wrong_Site, .<span class="dv">13</span>, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   13% 
6343.4 </code></pre>
</div>
</div>
</details>
<ol start="22" type="1">
<li>How would you interpret the 13<sup>th</sup> percentile (assuming the 13<sup>th</sup> percentile is $6343.40)?</li>
</ol>
<ul>
<li><ol type="a">
<li>100 of the lawsuits cost more than 13%.</li>
</ol></li>
<li><ol start="2" type="a">
<li>13% of the lawsuits cost the hospital over $6343.40.</li>
</ol></li>
<li><ol start="3" type="a">
<li>In 13% of the wrong-site lawsuits, hospitals had to pay $6343.40 or less.</li>
</ol></li>
<li><ol start="4" type="a">
<li>For 13% of the wrong-site lawsuits, the hospitals had to pay $6343.40 to the patient.</li>
</ol></li>
</ul>
<details>
<summary>
Solution
</summary>
<ul>
<li>Correct Answer: C</li>
</ul>
</details>
<p><br></p>
<ol start="23" type="1">
<li>Find P<sub>90</sub>.</li>
</ol>
<details>
<summary>
Solution
</summary>
<ul>
<li>$149,963.00</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(wrong_site<span class="sc">$</span>Wrong_Site, .<span class="dv">9</span>, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   90% 
149963 </code></pre>
</div>
</div>
</details>
<p><br></p>
<ol start="24" type="1">
<li>The quartiles divide a sorted list of data into four equal groups. So, each group contains 25% of the data. The first quartile is the value that is greater than or equal to 25% of the data. What is another name for this number?</li>
</ol>
<details>
<summary>
Solution
</summary>
<ul>
<li>The 25th percentile.</li>
</ul>
</details>
<p><br></p>
<ol start="25" type="1">
<li>What is the value of the third quartile?</li>
</ol>
<details>
<summary>
Solution
</summary>
<ul>
<li>$124,280.00</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(wrong_site<span class="sc">$</span>Wrong_Site, .<span class="dv">75</span>, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   75% 
124280 </code></pre>
</div>
</div>
</details>
<p><br></p>
<ol start="26" type="1">
<li>Half of the wrong-site lawsuits judgments were less than or equal to what value?</li>
</ol>
<details>
<summary>
Solution
</summary>
<ul>
<li>$68,552.00</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(wrong_site<span class="sc">$</span>Wrong_Site, .<span class="dv">5</span>, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  50% 
68552 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Or</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(wrong_site<span class="sc">$</span>Wrong_Site)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 68552</code></pre>
</div>
</div>
</details>
<p><br></p>
<ol start="27" type="1">
<li>The median is the middle observation in a sorted list of data. What percentile is always equal to the median?</li>
</ol>
<details>
<summary>
Solution
</summary>
<ul>
<li>The 50th percentile</li>
</ul>
</details>
<p>&nbsp;</p>
</div>
<p><br></p>
<section id="the-five-number-summary" class="level3">
<h3 class="anchored" data-anchor-id="the-five-number-summary">The Five-Number Summary</h3>
<p>Another way to summarize data is with the five-number summary. <strong>The five-number summary</strong> is comprised of the minimum, the first quartile, the second quartile (or median), the third quartile, and the maximum.</p>
<p>There is a very easy way to get the Five-Number Summary along with the mean and standard deviation. The <code>favstats()</code> function in the <code>mosaic</code> library gives us all of our <strong>fav</strong>orite <strong>stat</strong>istic<strong>s</strong>.</p>
<p>As before, we will have to install the <code>mosaic</code> library once, then load it when we want to use it.</p>
<div class="SoftwareHeading">
R Instructions
</div>
<div class="Software">
<p>&nbsp;&nbsp;<strong>To find the values for a five-number summary in R, do the following</strong></p>
<ul>
<li>Install the <code>mosaic</code> library (Only Once):</li>
</ul>
<pre><code>install.packages("mosaic")</code></pre>
<ul>
<li>Load the Library:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Input the data into the <code>favstats()</code> function:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(wrong_site<span class="sc">$</span>Wrong_Site)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> min    Q1 median     Q3    max     mean       sd   n missing
   0 29496  68552 124280 780575 80041.24 71403.83 411       0</code></pre>
</div>
</div>
<p><br></p>
</div>
<p><br></p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="28" type="1">
<li>Give the five-number summary for the Wrong Site data.
<details>
<summary>
Solution
</summary>
<center>
<span class="math display">\[\displaystyle{\$0,~~\$29,496;~~\$68,552;~~\$124,280;~~\$780,575}\]</span>
</center>
</details>
&nbsp;</li>
</ol>
</div>
<p><br></p>
<br>
<div class="message Caution">
Some students mistakenly include the mean in the five-number summary. The third value in the five-number summary is the median.
</div>
<p><br> <br></p>
</section>
<section id="boxplots" class="level3">
<h3 class="anchored" data-anchor-id="boxplots">Boxplots</h3>
<p>A <strong>boxplot</strong> is a graphical representation of the five-number summary. Unlike the mean or standard deviation, a boxplot is resistant to outliers. That means that it won’t be “pulled” one way or the other by extraordinarily large or small values in the data as will a mean, for instance. We will illustrate the process of making a boxplot using the wrong-site data.</p>
<p>Follow the steps below to learn how a boxplot relates to the five-number summary. Learning what each part of the boxplot represents will enable you to interpret the plot correctly.</p>
<p><strong>Step 01:</strong> To draw a boxplot, start with a number line.</p>
<p><img src="../Images/Lesson_2_Activity_6_BoxPlot_1.jpg"></p>
<p><strong>Step 02:</strong> Draw a vertical line segment above each of the quartiles.</p>
<p><img src="../Images/Lesson_2_Activity_6_BoxPlot_2.jpg"></p>
<p><strong>Step 03:</strong> Connect the tops and bottoms of the line segments, making a box.</p>
<p><img src="../Images/Lesson_2_Activity_6_BoxPlot_3.jpg"></p>
<p><strong>Step 04:</strong> Make a smaller mark above the values corresponding to the minimum and the maximum.</p>
<p><img src="../Images/Lesson_2_Activity_6_BoxPlot_4.jpg"></p>
<p><strong>Step 05:</strong> Draw a line from the left side of the box to the minimum, and draw another line from the right side of the box the maximum.</p>
<p><img src="../Images/Lesson_2_Activity_6_BoxPlot_5.jpg"></p>
<p><strong>Step 06:</strong> These last two lines look like whiskers, so this is sometimes called a box-and-whisker plot.</p>
<p><img src="../Images/Lesson_2_Activity_6_BoxPlot_6.jpg"></p>
<p><br></p>
<div class="SoftwareHeading">
R Instructions
</div>
<div class="Software" style="padding:10px;">
<p><strong>To create a boxplot in Excel, do the following</strong></p>
<ul>
<li>Load the data file. For this example, open the file <a href="./Data/WrongSiteWrongPatient.xlsx">WrongSiteWrongPatient.xlsx</a>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>wrong_site <span class="ot">&lt;-</span>  <span class="fu">import</span>(<span class="st">"https://github.com/byuistats/Math221D_Course/raw/main/Data/WrongSiteWrongPatient.xlsx"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Use the <code>boxplot()</code> function to get a boxplot:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(wrong_site<span class="sc">$</span>Wrong_Site)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="6-Spread_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We can make it a little nicer by adding labels to the x and y axes and adding a title as follows:</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(wrong_site<span class="sc">$</span>Wrong_Site, <span class="at">xlab=</span><span class="st">"Wrong Site"</span>, <span class="at">ylab=</span><span class="st">"Cost in $"</span>, <span class="at">main=</span><span class="st">"Boxplot of Costs of Operating on the Wrong Site"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="6-Spread_files/figure-html/unnamed-chunk-16-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
</div>
<p><br></p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="29" type="1">
<li>Create a histogram of the <strong>wrong-patient</strong> lawsuit data, located in column B of the file <a href="./Data/WrongSiteWrongPatient.xlsx">WrongSiteWrongPatient.xlsx</a>. What is the shape of the wrong-patient data?</li>
</ol>
<ol type="a">
<li>Skewed left</li>
<li>Symmetric</li>
<li>Skewed right</li>
<li>Multi-modal</li>
<li>Uniform</li>
</ol>
<details>
<summary>
Solution
</summary>
<p>To create the histogram, use the <code>histogram()</code> function on the data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">histogram</span>(wrong_site<span class="sc">$</span>Wrong_Patient)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="6-Spread_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From the histogram we clearly see most values bunched near the left and gradually fewer values as we move to the right along the number line, so the correct answer is ‘c.&nbsp;Skewed right’.</p>
</details>
<p><br></p>
</div>
<p>&nbsp;</p>
</section>
</section></section></main></div>
<p><br></p>
<p>Histograms are preferred to boxplots when visualizing one set of data. But side-by-side boxplots are a powerful way to compare data from different samples visually. For example, we may be interested in comparing the results of wrong-site lawsuits and wrong-patient lawsuits.</p>
<p>In the plot we can quickly see that a wrong-patient lawsuit resulted in the largest cost to the hospital, more than $1.2 million. However, in general, wrong-patient lawsuits tend to result in a lower cost to the hospital than wrong-site lawsuits.</p>
<div class="SoftwareHeading">
R Instructions
</div>
<div class="Software" style="padding:10px;">
<p><strong>To create side-by-side boxplots in Excel, do the following</strong></p>
<ul>
<li>Using the previously loaded data, <code>wrong_site</code>, use the <code>boxplot()</code> function with the column names separated by a comma, and add labels:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(wrong_site<span class="sc">$</span>Wrong_Patient, wrong_site<span class="sc">$</span>Wrong_Site, <span class="at">names=</span><span class="fu">c</span>(<span class="st">"Wrong Patient"</span>, <span class="st">"Wrong Site"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="6-Spread_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We will cover how to improve your charts even more a little later.</p>
<p><br></p>
</div>
<p><br></p>
<p><br></p>


<section id="summary-1" class="level2">
<h2 data-anchor-id="summary-1">Summary</h2>
<div class="SummaryHeading">
Remember…
</div>
<div class="Summary">
<ol type="1">
<li><p>A <strong>percentile</strong> is calculated in R using <code>quantile(data, 0.#)</code> where the <code>0.#</code> is the percentile written as a decimal number. So the 20th percentile would be written as 0.2.</p></li>
<li><p>A <strong>percentile</strong> is a number such that a specified percentage of the data are at or below this number. For example, if say 80% of college students were shorter than (or equal to) 70 inches tall in height, then the 80th percentile of heights of college students would be 70 inches.</p></li>
<li><p><strong>Standard deviation</strong> is calculated in R for a sample of data using <code>sd(data)</code>.</p></li>
<li><p>The <strong>standard deviation</strong> is a number that describes how spread out the data typically are from the mean of that data. A larger standard deviation means the data are more spread out from their mean than data with a smaller standard deviation. The standard deviation is never negative. A standard deviation of zero implies all values in the data set are exactly the same.</p></li>
<li><p>To compute any of the <strong>five-number summary</strong> values in R, use the R function <code>favstats(data)</code> which also includes the mean and standard deviation.</p></li>
<li><p>The <strong>five-number summary</strong> consists of (1) the minimum value in the data, (2) the first quartile (25th percentile) of the data, (3) the median of the data (50th percentile), (4) the third quartile (75th percentile) of the data, and (5) the maximum value occurring in the data.</p></li>
<li><p>To create a <strong>boxplot</strong> in R, use the <code>boxplot(data)</code> or for multiple columns <code>boxplot(data1, data2, names=c("Name of Column 1", "Name of Column 2))</code>.</p></li>
<li><p><strong>Boxplots</strong> are a visualization of the five-number summary of a data set.</p></li>
</ol>
</div>
<p><br></p>


</section>

 <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
 <!-- /content -->




</body></html>