---
title: "The Statistical Process-Practice"
---
```{r setup, include=FALSE}
# Ignore this bit of code.  This makes it so that you can render the qmd file even when there are errors in your code.
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, error = TRUE)
```



# 1 - "A sleep and a forgetting"

## The sitch:

The [Forgetting Curve](https://youtu.be/UpAq9EZpL5A?si=Y_wNRFDpaM1WsZKW) relates to how quickly we forget new information and suggests strategies for maximize retention.  Studies have shown that retention of classroom materials can drop as low as 58% within 15 minutes of class and within 44% after the first hour after class if there is no review of the material. This forgetting curve continues, so that within six days only 25% is remembered. 

Suppose your teacher wanted to test strategies for retention and invited you to participate in a study.  You would be randomly assigned to one of two groups.

Group 1 would be asked to review for ten minutes at three specific times: fifteen minutes after class, one hour after class, and two days after class.

Group 2 would not be asked to review the material at all.
Use the above information for all parts.

__Question__:  Which treatment group would be considered the control and why?  
__Answer__:

__Question__:  Before participating, your teacher gives you a short quiz and records your score out of 10.  What type of data (quantitative or categorical) is being recorded?  
__Answer__:

# 2 - "You see, but you do not observe"

For each of the following scenarios, explain which are observational studies and which are experiments and why:

1. A Telephone Poll asking people about whether or not they vaccinate their children

__Study Type__:

2. Administering the tuberculosis vaccination to one group and giving a placebo to another

__Study Type__:


3. A mailed survey asking people whether or not they received the tuberculosis vaccine

__Study Type__:

4. Randomly assigning 2 versions of an exam to a classroom

__Study Type__:

5. A sample of 504 patients in early stages of Alzheimer's disease is divided into two groups.  One group receives an experimental drug and the other a placebo.  The advance of the disease is tracked at one-month intervals over the next year.

__Study Type__:

# 3 - Will the real Jonas Salk please stand up

You want to become the next Jonas Salk and produce a vaccine that will help cure children of Respiratory Syncytial Virus (RSV).  You test the vaccine and compare it to a placebo and randomly choose one group of children to take the vaccine and one group to take the placebo.  

__Question__: What (or who) are the experimental units or subjects?  
__Answer__:  


__Question__: What are the treatments?  
__Answer__:  


__Question__: What is the population of this study?  
__Answer__:  


# 4 - Data Types

For each of the following examples, state whether or not the collected data are quantitative or categorical:

1. The number of people in a randomly selected classroom on campus

__Data Type__:  

2. The 3 most common brands of car found in the US

__Data Type__:  

3. The telephone number of a randomly selected business in town

__Data Type__:  

4. The time spent on hold calling customer service

__Data Type__:  


# Election year madness

In a recent election, one marketing research firm was asked by a special interest group to help estimate the proportion of Americans who supported a particular candidate.  From a list of all registered voters, 8000 names were randomly selected. An automated phone-call was made to each of the 8000 individuals selected asking them to answer a few questions indicating their voting preferences. The marketing firm received 2969 responses. 

__Question__:  What is the population of the study?  
__Answer__:  

__Question__:  What is the sample of the study?  
__Answer__:  


# How Random!

For each scenario, state which type of sampling scheme was used and explain why:

__Scenario 1__:  A study conducted by researchers from the Department of Education wanted to know the average debt of college students in the United States. In order to obtain a sample representative of all students, the researchers divided college students into the four classes (freshman, sophomore, junior, and senior) and then took a random sample of students from each class. 

__Sampling Scheme__:  
__Explanation__:  


__Scenario 2__: Students in an Introductory Statistics class at BYU-Idaho were studying prices of cold cereal at grocery stores in Rexburg. To get a sample of cold cereal prices, they went to Albertson's and rolled a die to decide which box from the left of the top shelf they would start on. They then recorded every 6th cereal after the first, moving from left to right down the shelves, recording the name, size, and price of each cereal in their sample. 

__Sampling Scheme__:  
__Explanation__:  


__Scenario 3__: A study is being planned in order to estimate the parts per million of a particular pollutant in a lake's water. 

__Question__:  How would you sample from the lake to get a representative sample?  
__Answer__:  

