<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.543">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Math221 Notebook - The Normal Distribution</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Math221 Notebook</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-unit-1" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Unit 1</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-unit-1">    
        <li class="dropdown-header">Data Literacy</li>
        <li>
    <a class="dropdown-item" href="../1-Data_Literacy/1-Course_Introduction.html">
 <span class="dropdown-text">Course Introduction</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../1-Data_Literacy/2-Stat_Process.html">
 <span class="dropdown-text">The Statistical Process</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../1-Data_Literacy/3-Statistical_Process_Practice.html">
 <span class="dropdown-text">The Statistical Process</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../1-Data_Literacy/4-Installing_R.html">
 <span class="dropdown-text">Installing R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../1-Data_Literacy/5-Shape_and_Center.html">
 <span class="dropdown-text">Describing Quantitative Data (Shape &amp; Center)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../1-Data_Literacy/6-Spread.html">
 <span class="dropdown-text">Describing Quantitative Data (Spread)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../1-Data_Literacy/7-Introducing_R_Practice.html">
 <span class="dropdown-text">Introducing R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../1-Data_Literacy/8-Summarizing_Data_Multiple_Groups.html">
 <span class="dropdown-text">Summarizing Data Part 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../1-Data_Literacy/9-Summarizing_Data_Practice.html">
 <span class="dropdown-text">Summarizing Data Part 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../1-Data_Literacy/10-AA_Data_Summaries.html">
 <span class="dropdown-text">Summarizing Data AA</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-unit-2" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Unit 2</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-unit-2">    
        <li class="dropdown-header">Into the Tidyverse</li>
        <li>
    <a class="dropdown-item" href="../2-Tidy_Data/01-Wrangling_Basics.html">
 <span class="dropdown-text">Intro to Data Wrangling</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../2-Tidy_Data/02-Filter.html">
 <span class="dropdown-text">filter()</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../2-Tidy_Data/03-Select.html">
 <span class="dropdown-text">select()</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../2-Tidy_Data/04-Tidyverse_Fundamentals.html">
 <span class="dropdown-text">Introducing the Tidyverse - Part 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href=".././2-Tidy_Data/05-Exploring_New_Data_With_Tidyverse.qmd">
 <span class="dropdown-text"></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../2-Tidy_Data/06-GGPlot_Intro.html">
 <span class="dropdown-text">Introducing GGPlot!</span></a>
  </li>  
        <li class="dropdown-header">Bonus Material</li>
        <li>
    <a class="dropdown-item" href="../2-Tidy_Data/Bonus_More_Tidy_Practice.html">
 <span class="dropdown-text">Level up your Tidy-ness</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../2-Tidy_Data/Bonus_Mutate.html">
 <span class="dropdown-text">mutate()</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../2-Tidy_Data/Bonus_GroupBy_Summarise.html">
 <span class="dropdown-text">group_by() + summarise()</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-unit-3" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Unit 3</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-unit-3">    
        <li class="dropdown-header">Fundamentals of Statistics</li>
        <li>
    <a class="dropdown-item" href="../3-Stat_Fundamentals/01-Intro_to_Probability.html">
 <span class="dropdown-text">Intro to Probability</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../3-Stat_Fundamentals/02-The_Normal_Distribution_Textbook.html">
 <span class="dropdown-text">The Normal Distribution</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../3-Stat_Fundamentals/03-Normal_Distribution_Workbook.html">
 <span class="dropdown-text">The Normal Distribution</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../3-Stat_Fundamentals/04-Normal_Probability_Practice.html">
 <span class="dropdown-text">Normal Probability Homework</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../3-Stat_Fundamentals/05-The_Central_Limit_Theorem.html">
 <span class="dropdown-text">The Distribution of Sample Means</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../3-Stat_Fundamentals/06-Central_Limit_Theorem_Practice.html">
 <span class="dropdown-text">Central Limit Theorem</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../3-Stat_Fundamentals/07-Prob_Calculations_for_Means.html">
 <span class="dropdown-text">Calculating Probabilities involving the Sample Mean</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../3-Stat_Fundamentals/08-CLT_Normal_Prob_for_Means.html">
 <span class="dropdown-text">Normal Probability Calculations for Means</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../3-Stat_Fundamentals/09-Prob_Calculations_for_Means_Practice.html">
 <span class="dropdown-text">Calculating Probabilities with Means</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../3-Stat_Fundamentals/10-Assessing_Normality.html">
 <span class="dropdown-text">Assessing Normality</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-unit-4" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Unit 4</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-unit-4">    
        <li class="dropdown-header">Statistical Tests - Part 1</li>
        <li>
    <a class="dropdown-item" href="../4-Statistical_Tests_Part1/01-Inference_for_mean_sigma_unknown.html">
 <span class="dropdown-text">Inference for a Mean - Sigma Unknown</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../4-Statistical_Tests_Part1/02-AA_Hypothesis_Conf_Int.html">
 <span class="dropdown-text">Don’t Take it Personally</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../4-Statistical_Tests_Part1/03-Paired_ttest.html">
 <span class="dropdown-text">Paired T-test Class Notes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../4-Statistical_Tests_Part1/05-Independent_2_sample_ttest.html">
 <span class="dropdown-text">Independent Two-sample T-test</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../4-Statistical_Tests_Part1/07-ANOVA_Intro.html">
 <span class="dropdown-text">Analysis of Variance (ANOVA)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../4-Statistical_Tests_Part1/09-AA_Unit4_Review.html">
 <span class="dropdown-text">Comparing Means</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-unit-5" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Unit 5</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-unit-5">    
        <li class="dropdown-header">Statistical Tests - Part 2</li>
        <li>
    <a class="dropdown-item" href="../5-Statistical_Tests_Part2/01-Bivariate_Data_Intro.html">
 <span class="dropdown-text">Introducing the Bivariate Data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../5-Statistical_Tests_Part2/02-Linear_Regression_Intro.html">
 <span class="dropdown-text">Simple Linear Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../5-Statistical_Tests_Part2/03-Regression_Practice.html">
 <span class="dropdown-text">Regression Practice</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../5-Statistical_Tests_Part2/05-Distribution_of_Phat.html">
 <span class="dropdown-text">Sampling Distribution of P_hat</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../5-Statistical_Tests_Part2/07-One_Sample_Proportion_Ztest.html">
 <span class="dropdown-text">One-sample Proportion Tests</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../5-Statistical_Tests_Part2/09-Two_Sample_Proportion_Ztest.html">
 <span class="dropdown-text">Two-sample Proportion Tests</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../5-Statistical_Tests_Part2/11-Chi_Square_Intro.html">
 <span class="dropdown-text">Chi-square Test of Independence</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../5-Statistical_Tests_Part2/13-AA_Who_Shot_First_Cat_Vars.html">
 <span class="dropdown-text">Who Shot First?</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-semester-project" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Semester Project</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-semester-project">    
        <li>
    <a class="dropdown-item" href="../6-Semester_Project/Importing_Data.html">
 <span class="dropdown-text">Downloading Data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../6-Semester_Project/Semester_Project_Instructions.html">
 <span class="dropdown-text">Semester Project</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-r-help" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">R Help</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-r-help">    
        <li>
    <a class="dropdown-item" href="https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf">
 <span class="dropdown-text">Tidyverse Cheat Sheet</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://r4ds.had.co.nz/transform.html">
 <span class="dropdown-text">R for Data Science</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../1-Data_Literacy/4-Installing_R.html">
 <span class="dropdown-text">Installing R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../2-Tidy_Data/06-GGPlot_Intro.html">
 <span class="dropdown-text">Introducing GGPlot!</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../2-Tidy_Data/01-Wrangling_Basics.html">
 <span class="dropdown-text">Intro to Data Wrangling</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../2-Tidy_Data/02-Filter.html">
 <span class="dropdown-text">filter()</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../2-Tidy_Data/03-Select.html">
 <span class="dropdown-text">select()</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../2-Tidy_Data/Bonus_Mutate.html">
 <span class="dropdown-text">mutate()</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../2-Tidy_Data/Bonus_GroupBy_Summarise.html">
 <span class="dropdown-text">group_by() + summarise()</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../6-Semester_Project/Importing_Data.html">
 <span class="dropdown-text">Downloading Data</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#lesson-outcomes" id="toc-lesson-outcomes" class="nav-link active" data-scroll-target="#lesson-outcomes">Lesson Outcomes</a></li>
  <li><a href="#normal-distributions-and-normal-computations" id="toc-normal-distributions-and-normal-computations" class="nav-link" data-scroll-target="#normal-distributions-and-normal-computations">Normal Distributions and Normal Computations</a>
  <ul class="collapse">
  <li><a href="#baseball-batting-averages" id="toc-baseball-batting-averages" class="nav-link" data-scroll-target="#baseball-batting-averages">Baseball Batting Averages</a></li>
  <li><a href="#density-curves" id="toc-density-curves" class="nav-link" data-scroll-target="#density-curves">Density Curves</a></li>
  </ul></li>
  <li><a href="#normal-probability-computations" id="toc-normal-probability-computations" class="nav-link" data-scroll-target="#normal-probability-computations">Normal Probability Computations</a>
  <ul class="collapse">
  <li><a href="#introduction-to-the-normal-probability-applet" id="toc-introduction-to-the-normal-probability-applet" class="nav-link" data-scroll-target="#introduction-to-the-normal-probability-applet">Introduction to the Normal Probability Applet</a></li>
  <li><a href="#converting-a-z-score-to-a-probability" id="toc-converting-a-z-score-to-a-probability" class="nav-link" data-scroll-target="#converting-a-z-score-to-a-probability">Converting a <span class="math inline">\(z\)</span>-score to a Probability</a></li>
  <li><a href="#finding-the-probability-of-being-between-two-values" id="toc-finding-the-probability-of-being-between-two-values" class="nav-link" data-scroll-target="#finding-the-probability-of-being-between-two-values">Finding the Probability of Being Between Two Values</a></li>
  <li><a href="#calculating-percentiles-using-a-normal-distribution" id="toc-calculating-percentiles-using-a-normal-distribution" class="nav-link" data-scroll-target="#calculating-percentiles-using-a-normal-distribution">Calculating Percentiles using a Normal Distribution</a></li>
  </ul></li>
  <li><a href="#roughly-assessing-normality-using-a-histogram" id="toc-roughly-assessing-normality-using-a-histogram" class="nav-link" data-scroll-target="#roughly-assessing-normality-using-a-histogram">Roughly Assessing Normality Using a Histogram</a>
  <ul class="collapse">
  <li><a href="#baseball-batting-averages-1" id="toc-baseball-batting-averages-1" class="nav-link" data-scroll-target="#baseball-batting-averages-1">Baseball Batting Averages</a></li>
  <li><a href="#body-temperatures" id="toc-body-temperatures" class="nav-link" data-scroll-target="#body-temperatures">Body Temperatures</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">The Normal Distribution</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="lesson-outcomes" class="level2">
<h2 class="anchored" data-anchor-id="lesson-outcomes">Lesson Outcomes</h2>
<p>By the end of this lesson, you should be able to:</p>
<ol type="1">
<li>State the properties of a normal distribution</li>
<li>Calculate the z-score for an individual observation, given the population mean and standard deviation</li>
<li>Interpret a z-score</li>
<li>Use the normal distribution to calculate probabilities for one observation</li>
<li>Approximate probabilities from a normal distribution using the 68-95-99.7 rule</li>
<li>Calculate a percentile using the normal distribution</li>
</ol>
<p><br></p>
</section>
<section id="normal-distributions-and-normal-computations" class="level2">
<h2 class="anchored" data-anchor-id="normal-distributions-and-normal-computations">Normal Distributions and Normal Computations</h2>
<section id="baseball-batting-averages" class="level3">
<h3 class="anchored" data-anchor-id="baseball-batting-averages">Baseball Batting Averages</h3>
<p><img src="../Images/Baseball.jpg"></p>
<p>In baseball, a player called the “pitcher” throws a ball to a player called the “batter.” The batter swings a wooden or metal bat and tries to hit the ball. A “hit” is made when the batter successfully hits the ball and runs to a point in the field called first base. A player’s batting average is calculated as the ratio of the number of hits a player makes divided by the number of times the player has attempted to hit the ball or in other words, been “at bat.” Sean Lahman reported the batting averages of several professional baseball players in the United States. (Lahman, 2010) The file <a href="../Data/BattingAverages.xlsx">BattingAverages.xlsx</a> contains his data.</p>
<p>The following histogram summarizes the batting averages for these professional baseball players:</p>
<p><img src="../Images/Lesson_03_Activity_06_Reading_1.jpg"></p>
<p>Notice the bell-shaped distribution of the data.</p>
<p>Suppose we want to estimate the probability that a randomly selected player will have a batting average that is greater than 0.280. One way to do this would be to find the proportion of players in the data set who have a batting average above 0.280. We can do this by finding the number of players who fall into each of the red-colored bins below and dividing this number by the total number of players.</p>
<p><img src="../Images/L03_A06_R02.jpg"></p>
<p>In other words, we could find the proportion of the total area of the bars that is shaded red out of the combined area of all the bars. This gives us the proportion of players whose batting averages are greater than 0.280.</p>
<p>Out of the 446 players listed, there are a total of 133 players with batting averages over 0.280. This suggests that the proportion of players whose batting average exceeds 0.280 is:</p>
<p><span class="math display">\[\displaystyle{\frac{133}{446}} = 0.298\]</span></p>
<p>Alternatively, we can use the fact that the data follow a bell-shaped distribution to find the probability that a player has a batting average above 0.280.</p>
</section>
<section id="density-curves" class="level3">
<h3 class="anchored" data-anchor-id="density-curves">Density Curves</h3>
<p>The bell-shaped curve superimposed on the histogram above is called a density curve. It is essentially a smooth histogram. Notice how closely this curve follows the observed data.</p>
<p>The density curve illustrated on the histogram of the batting average data is special. It is called a <strong>normal density curve</strong>. This density curve is symmetric and has a bell-shape.</p>
<p>The normal density curve is also referred to as a normal distribution or a “Gaussian” distribution (after Carl Friedrich Gauss.)</p>
<p>The normal density curve appears in many applications in business, nature, medicine, psychology, sociology, and more. We will use the normal density curve extensively in this course.</p>
<p>All density curves, including normal density curves, have two basic properties:</p>
<ol type="1">
<li>The total area under the curve equals 1.</li>
<li>The density curve always lies on or above the horizontal axis.</li>
</ol>
<p>Because of these two properties, the area under the curve can be treated as a probability. If we want to find the probability that a randomly selected baseball player will have a batting average between some range of values, we only need to find the area under the curve in that range. This is illustrated by the region shaded in blue in the figure below.</p>
<p><img src="../Images/L03_A06_R03.jpg"></p>
<p>A normal density curve is uniquely determined by its mean, <span class="math inline">\(\mu\)</span>, and its standard deviation, <span class="math inline">\(\sigma\)</span>. So, if random variables follow a normal distribution with a known mean and standard deviation, then we can calculate any probabilities related to that variable by finding the area under the curve.</p>
<p>When the mean of a normal distribution is 0 and its standard deviation is 1, we call it the <strong>standard normal distribution</strong>.</p>
<p>We will return to this example later, and we will find the area shaded in blue.</p>
<section id="characteristics-of-the-normal-curve" class="level4">
<h4 class="anchored" data-anchor-id="characteristics-of-the-normal-curve">Characteristics of the Normal Curve</h4>
<section id="introduction-to-z-scores" class="level5">
<h5 class="anchored" data-anchor-id="introduction-to-z-scores">Introduction to <span class="math inline">\(z\)</span>-scores</h5>
<p>In Ghana, the mean height of young adult women is normally distributed with mean <span class="math inline">\(159.0\)</span> cm and standard deviation <span class="math inline">\(4.9\)</span> cm. (Monden &amp; Smits, 2009) Serwa, a female BYU-Idaho student from Ghana, is <span class="math inline">\(169.0\)</span> cm tall. Her height is <span class="math inline">\(169.0 - 159.0 = 10\)</span> cm greater than the mean. When compared to the standard deviation, she is about two standard deviations (<span class="math inline">\(\approx 2 \times 4.9\)</span> cm) taller than the mean.</p>
<p>The heights of men are also normally distributed. The mean height of young adult men in Brazil is <span class="math inline">\(173.0\)</span> cm (“Oramento,” 2010), and the standard deviation for the population is <span class="math inline">\(6.3\)</span> cm. (Castilho &amp; Lahr, 2001) A Brazilian BYU-Idaho student, Gustavo, is <span class="math inline">\(182.5\)</span> cm tall. Compared to other Brazilians, he is taller than the mean height of Brazilian men.</p>
<div class="QuestionsHeading">
Answer the following question:
</div>
<div class="Questions">
<ol type="1">
<li>Approximately how many standard deviations above the mean is Gustavo’s height?</li>
</ol>
<details>
<summary>
Show/Hide Solution
</summary>
<ul>
<li>Gustavo’s height is <span class="math inline">\(182.5 - 173.0 = 9.5 \text{ cm  }\)</span> above the mean. The standard deviation of the height of Brazilian men is 6.3 cm, so his height is <span class="math inline">\(\displaystyle{ \frac{9.5}{6.3} =1.508 }\)</span> standard deviations above the mean.</li>
</ul>
</details>
</div>
<p><br></p>
</section>
<section id="computing-z-scores" class="level5">
<h5 class="anchored" data-anchor-id="computing-z-scores">Computing <span class="math inline">\(z\)</span>-scores</h5>
<p>When we examined the heights of Serwa and Gustavo, we compared their height to the standard deviation. If we look carefully at the steps we did, we subtracted the mean height for people of the same gender and nationality from each individual’s height, respectively.</p>
<p>This shows how much taller or shorter the person is than the mean height. In order to compare the height difference to the standard deviation, we divide the difference by the standard deviation. This gives the number of standard deviations the individual is above or below the mean.</p>
<p>For example, Serwa’s height is 169.0 cm. If we subtract the mean and divide by the standard deviation, we get <span class="math display">\[z = \frac{169.0 - 159.0}{4.9} = 2.041\]</span> We call this number a <span class="math inline">\(z\)</span>-score. The <span class="math inline">\(z\)</span>-score for a data value tells how many standard deviations away from the mean the observation lies. If the <span class="math inline">\(z\)</span>-score is positive, then the observed value lies above the mean. A negative <span class="math inline">\(z\)</span>-score implies that the value was below the mean.</p>
<p>We compute the <span class="math inline">\(z\)</span>-score for Gustavo’s height similarly, and obtain <span class="math display">\[z = \frac{182.5 - 173.0}{6.3} = 1.508\]</span> Gustavo’s <span class="math inline">\(z\)</span>-score is 1.508. As noted above, this is about one-and-a-half standard deviations above the mean. In general, if an observation <span class="math inline">\(x\)</span> is taken from a random process with mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span>, then the <span class="math inline">\(z\)</span>-score is <span class="math display">\[z = \frac{x -\mu }{\sigma}\]</span></p>
<p>The <span class="math inline">\(z\)</span>-score can be computed for data from any distribution, but it is most commonly applied to normally distributed data.</p>
</section>
<section id="rule-for-bell-shaped-distributions" class="level5">
<h5 class="anchored" data-anchor-id="rule-for-bell-shaped-distributions">68-95-99.7% Rule for Bell-shaped Distributions</h5>
<p>Heights of women (or men) in a particular population follow a normal distribution. Most people’s heights are close to the mean. A few are very tall or very short. We would like to make a more precise statement than this.</p>
<div class="Emphasis">
<p>For any bell-shaped distribution,</p>
<ul>
<li>68% of the data will lie within 1 standard deviation of the mean,</li>
<li>95% of the data will lie within 2 standard deviations of the mean, and</li>
<li>99.7% of the data will lie within 3 standard deviations of the mean.</li>
</ul>
<p>This is called the 68-95-99.7% Rule for Bell-shaped Distributions. Some statistics books refer to this as the Empirical Rule. <br></p>
</div>
<p><br></p>
<p><img src="../Images/L03_A06_R04.jpg"></p>
<p>Approximately 68% of the observations from a bell-shaped distribution will be between the values of <span class="math inline">\(\mu -~\sigma~\)</span>and <span class="math inline">\(\mu +~\sigma\)</span>. Consider the heights of young adult women in Ghana. We expect that about 68% of Ghanaian women have a height between the values of <span class="math display">\[\mu -~\sigma = 159.0 - 4.9 = 154.1~\text{cm}\]</span> and <span class="math display">\[\mu +~\sigma = 159.0 + 4.9 = 163.9~\text{cm}.\]</span></p>
<p>So, if a female is chosen at random from all the young adult women in Ghana, about 68% of those chosen will have a height between 154.1 and 163.9 cm. Similarly, 95% of the women’s heights will be between the values of <span class="math display">\[\mu - 2\sigma = 159.0 - 2(4.9) = 149.2~\text{cm}\]</span> and <span class="math display">\[\mu + 2\sigma = 159.0 + 2(4.9) = 168.8~\text{cm}.\]</span></p>
<p>Finally, 99.7% of the women’s heights will be between <span class="math display">\[\mu - 3\sigma = 159.0 - 3(4.9) = 144.3~\text{cm}\]</span> and <span class="math display">\[\mu + 3\sigma = 159.0 + 3(4.9) = 173.7~\text{cm}.\]</span></p>
</section>
</section>
<section id="unusual-events" class="level4">
<h4 class="anchored" data-anchor-id="unusual-events">Unusual Events</h4>
<p>If a <span class="math inline">\(z\)</span>-score is extreme (either a large positive number or a large negative number), then that suggests that that observed value is very far from the mean. The 68-95-99.7% rule states that 95% of the observed data values will be within two standard deviations of the mean. This means that 5% of the observations will be more than 2 standard deviations away from the mean (either to the left or to the right).</p>
<p>We define an <strong>unusual observation</strong> to be something that happens less than 5% of the time. For normally distributed data, we determine if an observation is unusual based on its <span class="math inline">\(z\)</span>-score. We call an observation unusual if <span class="math inline">\(z &lt; -2\)</span> or if <span class="math inline">\(z &gt; 2\)</span>. In other words, we will call an event unusual if the absolute value of its <span class="math inline">\(z\)</span>-score is greater than 2.</p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol start="2" type="1">
<li>Out of Serwa and Gustavo, who is physically taller?</li>
</ol>
<details>
<summary>
Show/Hide Solution
</summary>
<ul>
<li>Gustavo is taller. He is 182.5 cm tall, and Serwa is 169.0 cm tall.</li>
</ul>
</details>
<ol start="3" type="1">
<li>Relative to their own gender and nationality, who is relatively taller?</li>
</ol>
<details>
<summary>
Show/Hide Solution
</summary>
<ul>
<li>Relative to other Ghanaian women, Serwa is very tall. Gustavo is tall relative to Brazilian men, but relative to people of his gender and nationality, he is not relatively taller than Serwa. Serwa has a higher <span class="math inline">\(z\)</span>-score.</li>
</ul>
</details>
<ol start="4" type="1">
<li>Are either of these heights unusual?</li>
</ol>
<details>
<summary>
Show/Hide Solution
</summary>
<ul>
<li>Serwa’s height is unusual. Her <span class="math inline">\(z\)</span>-score is: <span class="math inline">\(z = 2.041\)</span> This is more than two standard deviations away from the mean. Gustavo’s height is not unusual. His <span class="math inline">\(z\)</span>-score is less than two standard deviations away from the mean.</li>
</ul>
</details>
</div>
<center>
“Piled Higher and Deeper” by Jorge Cham
</center>
<p><br></p>
<p><img src="../Images/Phd1030.png"></p>
</section>
</section>
</section>
<section id="normal-probability-computations" class="level2">
<h2 class="anchored" data-anchor-id="normal-probability-computations">Normal Probability Computations</h2>
<p>An important part of the practice of statistics is finding areas under a normal curve. The area under a normal curve, say, to the left of a value, gives the probability of obtaining an observation less than (or equal to) that value. This is an example of converting a value to an area. It is also important to convert an area to a value. For example, if you want to find the 40th percentile for data that follow a normal distribution, you find the value of the observation such that the area (under the curve) to the left of this value is 0.40.</p>
<section id="introduction-to-the-normal-probability-applet" class="level3">
<h3 class="anchored" data-anchor-id="introduction-to-the-normal-probability-applet">Introduction to the Normal Probability Applet</h3>
<p>The Normal Probability Applet is a visualization program offering statistics students insights and computations for the relationship between <span class="math inline">\(z\)</span>-scores and areas under the standard normal curve. You can find a link to this applet <a href="https://byuimath.com/apps/normprob.html">here</a>. This app is also compatible to use on your phone, iPad, and other mobile devices. The app is stored at . If you want a copy you can open from your desktop, just right click the link and save it to your computer.</p>
<p>To use this applet, follow these instructions:</p>
<ul>
<li>Click on an area below the curved line to shade/unshade the region.</li>
<li>Click and drag the red lines to adjust the <span class="math inline">\(z\)</span>-scores and obtain the area.</li>
<li>Type a <span class="math inline">\(z\)</span>-score into one of the bottom input boxes and hit “Enter” to get an area.</li>
<li>Type in an area and hit “Enter” to get a <span class="math inline">\(z\)</span>-score.</li>
</ul>
<center>
<div class="iframe-container" width="90%">
<iframe src="https://byuimath.com/apps/normprob.html?width=600&amp;z=1&amp;height=400&amp;left=1&amp;mid=0&amp;right=1&amp;area=a&amp;static=0&amp;title=1&amp;border=0" frameborder="0" width="650" height="450" data-external="1">
</iframe>
</div>
</center>
</section>
<section id="converting-a-z-score-to-a-probability" class="level3">
<h3 class="anchored" data-anchor-id="converting-a-z-score-to-a-probability">Converting a <span class="math inline">\(z\)</span>-score to a Probability</h3>
<p>Using this applet we can calculate proportions and probabilities based on the area under the normal curve. For the following examples, please open the <a href="https://byuimath.com/apps/normprob.html" target="_blank">Normal Probability Applet</a> and practice using it to find areas under the curve.</p>
<p>The Normal Probability Applet is nice for visualizing areas under the curve. However, it has significant limitations. In this class, we will use R to do the heavy lifting. The pnorm(x, <span class="math inline">\(\mu\)</span>, <span class="math inline">\(\sigma\)</span>) function calculates areas under the curve the normal distribution with mean, <span class="math inline">\(\mu\)</span>, and standard deviation, <span class="math inline">\(\sigma\)</span>, for a given x. The <code>p</code> in <code>pnorm()</code> stands for probability and <code>norm</code> obviously stands for the normal distribution.</p>
<p>By default, <code>pnorm()</code> gives the area of the curve to the <em>LEFT</em> of the value, <span class="math inline">\(x\)</span>, for a normal distribution with a mean, <span class="math inline">\(\mu\)</span>, and standard deviation, <span class="math inline">\(\sigma\)</span>.</p>
<p>We can calculate probabilities directly in the original units of the data, or use the z-score with a <span class="math inline">\(\mu=0\)</span> and <span class="math inline">\(\sigma=1\)</span>: <code>pnorm(z)</code>.</p>
<p><strong>NOTE</strong>: <code>pnorm()</code> has a default value for the mean, <span class="math inline">\(\mu = 0\)</span> and standard deviation, <span class="math inline">\(\sigma = 1\)</span> so we don’t have to input those values when we use a z-score with the <strong>standard normal distribution</strong>.</p>
<section id="heights-of-ghanaian-women" class="level4">
<h4 class="anchored" data-anchor-id="heights-of-ghanaian-women">Heights of Ghanaian Women</h4>
<p>We will use the example of Serwa’s height to find the proportion of young Ghanaian women who are shorter than Serwa. Recall that for the height of young Ghanaian women, the population mean is 159.0 cm and the population standard deviation is 4.9 cm. Serwa’s height is 169.0 cm. We found the <span class="math inline">\(z\)</span>-score of Serwa’s height as:</p>
<p><span class="math display">\[z = \frac{x -\mu}{\sigma} = \frac{169.0- 159.0}{4.9} = 2.041\]</span></p>
<p>What proportion of young Ghanaian women reach a height that is at or below 169 cm? To answer this question, we need to find the area under a normal density curve (i.e.&nbsp;the probability) that is to the left of <span class="math inline">\(z = 2.041\)</span>.</p>
<p>To find the area under a normal curve corresponding to a <span class="math inline">\(z\)</span>-score of <span class="math inline">\(2.041\)</span>, do the following:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">2.041</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9793746</code></pre>
</div>
</div>
<center>
<div width="90%">
<div class="iframe-container" width="90%">
<iframe src="https://byuimath.com/apps/normprob.html?width=600&amp;z=2.041&amp;height=400&amp;left=1&amp;mid=1&amp;right=0&amp;area=a&amp;static=1&amp;title=1&amp;border=0" frameborder="0" width="650" height="450" data-external="1">
</iframe>
</div>
</div>
</center>
<p><strong>NOTE</strong>: The area to the left of our chosen <span class="math inline">\(z\)</span>-score is also the probability that a randomly selected woman will be shorter than Serwa. The probability that a randomly selected Ghanaian woman will be shorter than Serwa is <span class="math inline">\(0.979\)</span>, or <span class="math inline">\(97.9\%\)</span>.</p>
<p><nowiki>*</nowiki>Remember that in this course, unless otherwise specified, we round to three decimal places.</p>
</section>
<section id="baseball-averages" class="level4">
<h4 class="anchored" data-anchor-id="baseball-averages">Baseball Averages</h4>
<p>We now return to the example of the baseball batting averages. We want to find the probability that a randomly selected player will have a batting average that is <em>above</em> 0.280. The population mean is 0.261 and the population standard deviation is 0.034. We can use this information to find a <span class="math inline">\(z\)</span>-score. Then we use the applet to find the area under the normal curve to the right of this <span class="math inline">\(z\)</span>-score.</p>
<p><span class="math display">\[z = \frac{x -\mu}{\sigma} = \frac{0.280 - 0.261}{0.034} = 0.559\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fl">0.280</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fl">0.261</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fl">0.034</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> (x<span class="sc">-</span>mu)<span class="sc">/</span>sigma</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Area to the LEFT:</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(x, mu, sigma)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7118589</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Equivilantly:</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(z)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7118589</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Area to the RIGHT</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">pnorm</span>(x, mu, sigma)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2881411</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">pnorm</span>(z)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2881411</code></pre>
</div>
</div>
<p>Using the Applet, type the <span class="math inline">\(z\)</span>-score of <span class="math inline">\(0.559\)</span> in one of the boxes below the horizontal axis in the applet. Click on the areas under the curve until only the region on the right is highlighted in blue.</p>
<p><img src="../Images/Batting_average_z-score.PNG"></p>
<p>The area under the curve to the right of <span class="math inline">\(z = 0.559\)</span> is <span class="math inline">\(0.288\)</span>. This is the probability that a randomly selected player will have a batting average that is greater than 0.280. (Note: It is a coincidence that the area, 0.288, is close to the batting average of 0.280. There is no significance in this.)</p>
<p>Notice that the area shaded in blue above 0.288 is very close to the area we found when we looked at the area represented by the bars of the histogram 0.298 that was shaded in red above.</p>
</section>
</section>
<section id="finding-the-probability-of-being-between-two-values" class="level3">
<h3 class="anchored" data-anchor-id="finding-the-probability-of-being-between-two-values">Finding the Probability of Being Between Two Values</h3>
<p>The normal probability applet allows us to find the probability of being between two values as long as they are on opposite sides of the mean and equally distanced from the mean. By calculating two z-scores, one for each value, and then shading the area between them on the applet, we can find the probability. This is severely limiting.</p>
<p>Below, we demonstrate how to find the area between <em>any</em> two values in a normal distribution.</p>
<section id="heights-of-ghanaian-women-1" class="level4">
<h4 class="anchored" data-anchor-id="heights-of-ghanaian-women-1">Heights of Ghanaian Women</h4>
<p>What is the probability that a randomly selected young Ghanaian women will be between 150.0 cm and 163.0 cm tall? Recall that the average height for young Ghanaian women is <span class="math inline">\(\mu=159.0\)</span> cm and the population standard deviation is <span class="math inline">\(\sigma=4.9\)</span> cm.</p>
<p>We want to find the probability that a randomly selected woman’s height is between <span class="math inline">\(150.0\)</span> cm and <span class="math inline">\(165.0\)</span> cm. To do this we find the <span class="math inline">\(z\)</span>-score for both values:</p>
<p><span class="math display">\[z_1 = \frac{x- \mu}{\sigma} = \frac{150.0 - 159.0}{4.9} = -1.837\]</span> <span class="math display">\[z_2 = \frac{x - \mu}{\sigma} = \frac{165.0 -159.0}{4.9} = 1.22\]</span></p>
<p>We now answer the question by finding the area under the normal density curve (i.e.&nbsp;the probability) to the left of <span class="math inline">\(z = 1.22\)</span> which is <span class="math inline">\(0.8888\)</span> and also the area under the normal density curve to the left of <span class="math inline">\(z = -1.837\)</span> which is <span class="math inline">\(0.033\)</span>. To find the area between <span class="math inline">\(z = 1.22\)</span> and <span class="math inline">\(z = -1.837\)</span>, we subtract the smaller area from the larger.</p>
<p><span class="math display">\[0.8888 - 0.0331 = 0.8557\]</span></p>
<p>So the probability that the height of a randomly selected young Ghanaian woman will be between 150.0 cm and 165.0 cm is <span class="math inline">\(0.8558\)</span>. This is the same as the proportion of all young Ghanaian women who are between 150.0 and 165.0 cm tall.</p>
<p>To find the probability of being between <em>any</em> 2 numbers for a normal distribution with mean, <span class="math inline">\(\mu\)</span>, and standard deviation, <span class="math inline">\(\sigma\)</span>, we can use the following R code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>value1 <span class="ot">&lt;-</span> <span class="dv">150</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>value2 <span class="ot">&lt;-</span> <span class="dv">165</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="dv">159</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fl">4.9</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(value2, <span class="at">mean =</span> mu, <span class="at">sd =</span> sigma) <span class="sc">-</span> <span class="fu">pnorm</span>(value1, <span class="at">mean =</span> mu, <span class="at">sd =</span> sigma)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8564917</code></pre>
</div>
</div>
<p><strong>NOTE</strong>: Value 1 is the lower of the two values and Value 2 is the higher value. Also, this answer is slightly different than above due to when you round. This answer is more accurate because we rounded at the end of the probability calculations rather than rounding the z-scores, then calculating probabilities.</p>
</section>
</section>
<section id="calculating-percentiles-using-a-normal-distribution" class="level3">
<h3 class="anchored" data-anchor-id="calculating-percentiles-using-a-normal-distribution">Calculating Percentiles using a Normal Distribution</h3>
<p>A percentile is a number such that a specified percentage of the population are at or below this number. For example, the 25<sup>th</sup> percentile is the number in a data set that is greater than or equal to 25% of all the values in the data set.</p>
<p>We can find percentiles <em>for a given dataset</em> by using the <code>quantile()</code> function as described in the chapter on <a href="https://byuistats.github.io/Math221D_Course/Textbook/Spread.html">summarizing data</a></p>
<p>However, to calculate percentiles <em>from a normal distribution</em>, we use the <code>qnorm(percentile, mu, sigma)</code> function.</p>
<p><strong>NOTE</strong>: R typically uses the word <em>quantile</em> when referring to <em>percentiles</em>. So the <span class="math inline">\(q\)</span> in <code>qnorm()</code> stands for <em>quantile</em>.</p>
<p>To find the <em>height</em> of a Ghanaian woman corresponding to the 90<sup>th</sup> percentile:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(.<span class="dv">90</span>, <span class="at">mean =</span> <span class="dv">159</span>, <span class="at">sd =</span> <span class="fl">4.9</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 165.2796</code></pre>
</div>
</div>
<p>The 90<sup>th</sup> percentile of the heights averages is 165.2796. That means that 90% of the Ghanaian women are shorter than 165.2796 cm tall.</p>
<p><br></p>
</section>
</section>
<section id="roughly-assessing-normality-using-a-histogram" class="level2">
<h2 class="anchored" data-anchor-id="roughly-assessing-normality-using-a-histogram">Roughly Assessing Normality Using a Histogram</h2>
<section id="baseball-batting-averages-1" class="level3">
<h3 class="anchored" data-anchor-id="baseball-batting-averages-1">Baseball Batting Averages</h3>
<p>Consider the data on the batting averages of Major League Baseball players. The histogram of the batting averages showed a distinct bell-shaped curve.</p>
<p><img src="../Images/Picture6.jpg"></p>
<p>Later in the course, we will learn a better way to assess normality. For now, we use histograms as a rough way to look for symmetry.</p>
<div class="SoftwareHeading">
R Instructions
</div>
<div class="Summary">
<p><strong>Here is a refresher of how to make a Histogram in R</strong></p>
<p>For more detailed instructions revisit <a href="../docs/1-Data_Literacy/8-Summarizing_Data_Multiple_Groups.html">Summarizing Data</a></p>
<ol type="1">
<li>Read in the data</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rio)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>bat_avg <span class="ot">&lt;-</span> <span class="fu">import</span>(<span class="st">"https://github.com/byuistats/Math221D_Course/raw/main/Data/BattingAverages.xlsx"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li>Use <code>histogram(data$column_name)</code> where <code>column_name</code> refers to the column you would like to use to create a histogram.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">histogram</span>(bat_avg<span class="sc">$</span>BattingAvg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-The_Normal_Distribution_Textbook_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="3" type="1">
<li>Customize your graph to make it presentation worthy by adding labels and modifying colors:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">histogram</span>(bat_avg<span class="sc">$</span>BattingAvg, <span class="at">main =</span> <span class="st">"Distribution of Batting Averages"</span>, <span class="at">xlab =</span> <span class="st">"Batting Average"</span>, <span class="at">ylab =</span> <span class="st">""</span>, <span class="at">col =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-The_Normal_Distribution_Textbook_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
</div>
<p><br></p>
</section>
<section id="body-temperatures" class="level3">
<h3 class="anchored" data-anchor-id="body-temperatures">Body Temperatures</h3>
<p>A group of researchers led by Philip A. Mackowiak, MD, conducted a study to assess the true mean body temperatures of healthy adults. They selected n = 148 subjects between the ages of 18 and 40 years old, representative of the general population.</p>
<p>Each volunteer was given a physical to assure that they were not ill at the time of the data collection. Their axillary (under the arm) body temperature was measured and reported in a paper published in the Journal of the American Medical Association. [1] These data were extracted and are presented in the file <a href="../Data/BodyTemp.xlsx">BodyTemp</a>. The body temperatures are given in degrees Fahrenheit.</p>
<div class="QuestionsHeading">
Answer the following questions:
</div>
<div class="Questions">
<ol type="1">
<li>Make a histogram of the body temperature data.</li>
</ol>
<details>
<summary>
Show/Hide Solution
</summary>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rio)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>body_temp <span class="ot">&lt;-</span> <span class="fu">import</span>(<span class="st">"https://github.com/byuistats/Math221D_Course/raw/main/Data/BodyTemp.xlsx"</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="fu">histogram</span>(body_temp<span class="sc">$</span>BodyTemp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-The_Normal_Distribution_Textbook_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</details>
<ol start="2" type="1">
<li>Based on your histogram, what is the shape of the distribution of these data?</li>
</ol>
<details>
<summary>
Show/Hide Solution
</summary>
<ul>
<li>The data appear to be normally distributed.</li>
</ul>
</details>
<ol start="3" type="1">
<li>Calculate the following numerical summaries of the data: sample mean, sample standard deviation, and sample size.</li>
</ol>
<details>
<summary>
Show/Hide Solution
</summary>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(body_temp<span class="sc">$</span>BodyTemp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  min   Q1 median   Q3   max     mean        sd   n missing
 96.2 97.8   98.3 98.7 100.8 98.23446 0.7375924 148       0</code></pre>
</div>
</div>
<p>The sample mean is 98.23, sample standard deviation is 0.738, and sample size is n = 148.</p>
</details>
<p><br></p>
</div>
<p><br></p>
</section>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<div class="SummaryHeading">
Remember…
</div>
<div class="Summary">
<ol type="1">
<li><p>A <strong>normal density curve</strong> is symmetric and bell-shaped with a mean of <span class="math inline">\(\mu\)</span> and a standard deviation of <span class="math inline">\(\sigma\)</span>. The curve lies above the horizontal axis and the total area under the curve is equal to 1. A <strong>standard normal distribution</strong> has a mean of 0 and a standard deviation of 1.</p></li>
<li><p>A <strong>z-score</strong> is calculated as:</p></li>
</ol>
<p><span class="math display">\[\displaystyle{z = \frac{\text{value}-\text{mean}}{\text{standard deviation}} = \frac{x-\mu}{\sigma}}\]</span></p>
<ol start="3" type="1">
<li><p>A <strong>z-score</strong> tells us how many standard deviations above (<span class="math inline">\(+Z\)</span>) or below (<span class="math inline">\(-Z\)</span>) the mean (<span class="math inline">\(\mu\)</span>) a given value (<span class="math inline">\(x\)</span>) is.</p></li>
<li><p>To calculate probabilities for a normal distribution with mean, <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span> for a given observation <span class="math inline">\(x\)</span>, use <code>pnorm(x, mu, sigma)</code> or <code>1-pnorm(x, mu, sigma)</code> to get the desired probability (below, above). Alternatively, calculate the <span class="math inline">\(z\)</span>-score and use <code>pnorm(z)</code> or <code>1-pnorm(z)</code>. In every case, the <strong>probability is</strong> given by the <strong>Area</strong> under the curve.</p></li>
<li><p>The <strong>68-95-99.7% rule</strong> states that when data are normally distributed, approximately 68% of the population lies within <span class="math inline">\(z=1\)</span> standard deviation (<span class="math inline">\(\sigma\)</span>) from the mean, approximately 95% of the data lie within <span class="math inline">\(z=2\)</span> standard deviations from the mean, and approximately 99.7% of the data lie within <span class="math inline">\(z=3\)</span> standard deviations from the mean. For example, this rule approximates that 2.5% of observations will be less than a z-score of <span class="math inline">\(z=-2\)</span>.</p></li>
<li><p>Percentiles can be calculated using the <code>qnorm(percentile, mu, sigma)</code> function.</p></li>
</ol>
<p><br></p>
</div>
<p><br></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>